# This file is generated by hack/update.rb. Edit packages.yml instead.
class AgentNotes < Formula
  desc "Store and inspect repository review notes"
  homepage "https://github.com/roshbhatia/agent-notes"
  url "https://github.com/roshbhatia/agent-notes/releases/download/v0.1.0/agent-notes_0.1.0_darwin_arm64.tar.gz"
  sha256 "9a2dfd7bf032c2a3f5e895356e1733312dfb15013aa926e432488b7c469e6727"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/agent-notes/releases/download/v0.1.0/agent-notes_0.1.0_darwin_arm64.tar.gz"
      sha256 "9a2dfd7bf032c2a3f5e895356e1733312dfb15013aa926e432488b7c469e6727"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/agent-notes/releases/download/v0.1.0/agent-notes_0.1.0_linux_arm64.tar.gz"
      sha256 "ec1d49b76d8de8e44f040f6f723823b61ce6104c62e33af80d14168f08b85ed9"
    end
    on_intel do
      url "https://github.com/roshbhatia/agent-notes/releases/download/v0.1.0/agent-notes_0.1.0_linux_amd64.tar.gz"
      sha256 "354923527ba8e2fb3954646096d951f50a69b363601930c4bc650a9ca9a2fc61"
    end
  end

  def install
    libexec.install "note"
    (bin/"note").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/note" "$@"
    SH
    (bin/"note").chmod 0755
  end

  test do
    assert_match "note", shell_output("#{bin}/note --help 2>&1")
  end
end
