# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderHermes < Formula
  desc "Hermes Agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_hermes_0.8.0_darwin_arm64.tar.gz"
  sha256 "4c5b7a0bf4b14d77e4ae78857767d4238e71a918534a9816ce8ee6260c7bca9d"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_hermes_0.8.0_darwin_arm64.tar.gz"
      sha256 "4c5b7a0bf4b14d77e4ae78857767d4238e71a918534a9816ce8ee6260c7bca9d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_hermes_0.8.0_linux_arm64.tar.gz"
      sha256 "0f6b41807b26571c8186d3da12af96426eb83af15c38b0f6abb2fee923afc659"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_hermes_0.8.0_linux_amd64.tar.gz"
      sha256 "654b9f1d2095fa265d6f19d6b59a5fbc562c09490406866110bb4d24a14d55d4"
    end
  end

  def install
    bin.install "ask-provider-hermes"
    (share/"ask/providers/hermes").install "share/ask/providers/hermes/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-hermes"
  end
end
