# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderHermes < Formula
  desc "Replay an offline token parser review with hermes"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_hermes_0.7.1_darwin_arm64.tar.gz"
  sha256 "a7bc4639fe6050658379553319200de31aa771457349fafbb944fa0c5150bc07"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_hermes_0.7.1_darwin_arm64.tar.gz"
      sha256 "a7bc4639fe6050658379553319200de31aa771457349fafbb944fa0c5150bc07"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_hermes_0.7.1_linux_arm64.tar.gz"
      sha256 "ec865f559e3a67a3cdf5d0e0541fd14113731f81498c0070a6030ba03236cb2e"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_hermes_0.7.1_linux_amd64.tar.gz"
      sha256 "2f5c0b5e178902a62d8ccfe42d9b049a1ccbb78eeedb9248f7d5ed23b50d33b0"
    end
  end

  def install
    bin.install "ask-provider-hermes"
    (share/"ask/providers/hermes").install "share/ask/providers/hermes/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-hermes"
  end
end
