# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderAntigravity < Formula
  desc "Antigravity CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_antigravity_0.8.0_darwin_arm64.tar.gz"
  sha256 "bf737c9f7f3788341003a6f91bfda3137b4a5d4bebecfeadf46c86332d4f8ddb"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_antigravity_0.8.0_darwin_arm64.tar.gz"
      sha256 "bf737c9f7f3788341003a6f91bfda3137b4a5d4bebecfeadf46c86332d4f8ddb"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_antigravity_0.8.0_linux_arm64.tar.gz"
      sha256 "6f09df829604e86727057147b94638f7d9ec9ba25f6f9dd72c24eff194c3b899"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_antigravity_0.8.0_linux_amd64.tar.gz"
      sha256 "5785d7b1cc02ea6021e838cbf84eaca927d2591329da92a3526621e4c9ab651a"
    end
  end

  def install
    bin.install "ask-provider-antigravity"
    (share/"ask/providers/antigravity").install "share/ask/providers/antigravity/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-antigravity"
  end
end
