# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderAntigravity < Formula
  desc "Antigravity CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_antigravity_0.7.2_darwin_arm64.tar.gz"
  sha256 "49eab9126dfb57cfbfd9b3b533c5bfd5087b645ae50b778c8bbed9285861be4d"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_antigravity_0.7.2_darwin_arm64.tar.gz"
      sha256 "49eab9126dfb57cfbfd9b3b533c5bfd5087b645ae50b778c8bbed9285861be4d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_antigravity_0.7.2_linux_arm64.tar.gz"
      sha256 "06e72fe73b4dafad72da825e376e6ac77464010e40045bec9d6428bb045e2def"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_antigravity_0.7.2_linux_amd64.tar.gz"
      sha256 "8cdcddc31a22a1f7f78617f55380a67140a5acbae1df6a1581dc2eac2a4db03f"
    end
  end

  def install
    bin.install "ask-provider-antigravity"
    (share/"ask/providers/antigravity").install "share/ask/providers/antigravity/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-antigravity"
  end
end
