# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCrush < Formula
  desc "Crush CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_crush_0.8.0_darwin_arm64.tar.gz"
  sha256 "e4a1bed60e7c374f04ea3279d4dc1b5b57ff8ceace08e30c8c58d85f7aaa23a7"
  license "MIT"

  depends_on "charmbracelet/tap/crush"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_crush_0.8.0_darwin_arm64.tar.gz"
      sha256 "e4a1bed60e7c374f04ea3279d4dc1b5b57ff8ceace08e30c8c58d85f7aaa23a7"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_crush_0.8.0_linux_arm64.tar.gz"
      sha256 "3525c2159c61f967db25436141514851914c10801b05d0a7ee3689bd9b486ebb"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_crush_0.8.0_linux_amd64.tar.gz"
      sha256 "3ff7d5ffaa30de127f649db381d4dc014667aabec3fd4207bf2e22c3dbe9b0c5"
    end
  end

  def install
    bin.install "ask-provider-crush"
    (share/"ask/providers/crush").install "share/ask/providers/crush/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-crush"
  end
end
