# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderDevin < Formula
  desc "Devin CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_devin_0.8.0_darwin_arm64.tar.gz"
  sha256 "3f2fead07766ca75c8815d3f9325d686bc07f5403096a1c6648f974218523b93"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_devin_0.8.0_darwin_arm64.tar.gz"
      sha256 "3f2fead07766ca75c8815d3f9325d686bc07f5403096a1c6648f974218523b93"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_devin_0.8.0_linux_arm64.tar.gz"
      sha256 "65a5a5c64d672300056345f80174ce7afe9f9e4ac84f80b53aa89e7b99afbdaa"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_devin_0.8.0_linux_amd64.tar.gz"
      sha256 "3568ffb2e948fde2a6b0300652e167fb113cacc4fccf388b39a5055d0bb18a2c"
    end
  end

  def install
    bin.install "ask-provider-devin"
    (share/"ask/providers/devin").install "share/ask/providers/devin/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-devin"
  end
end
