# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCrush < Formula
  desc "Replay an offline token parser review with crush"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_crush_0.7.1_darwin_arm64.tar.gz"
  sha256 "2d15ec168142b5c1fdd479769c80f8451ead1b23928391369f965aa7ea5bff13"
  license "MIT"

  depends_on "crush"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_crush_0.7.1_darwin_arm64.tar.gz"
      sha256 "2d15ec168142b5c1fdd479769c80f8451ead1b23928391369f965aa7ea5bff13"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_crush_0.7.1_linux_arm64.tar.gz"
      sha256 "1e4d6fa828947b77655f871df03ac737a8123c7992c611f71138abf8119778cb"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_crush_0.7.1_linux_amd64.tar.gz"
      sha256 "2631a72665486294c685cebf2dfe5d71c061568f314644237fb921cb35056655"
    end
  end

  def install
    bin.install "ask-provider-crush"
    (share/"ask/providers/crush").install "share/ask/providers/crush/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-crush"
  end
end
