# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskAll < Formula
  desc "All providers for ask"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_0.7.1_darwin_arm64.tar.gz"
  sha256 "0ea7dba0248bd5f197f66f0f2f644b7b12577302fe517483f34a932c60112c66"
  license "MIT"

  depends_on "roshbhatia/tap/ask"
  depends_on "roshbhatia/tap/ask-provider-antigravity"
  depends_on "roshbhatia/tap/ask-provider-claude"
  depends_on "roshbhatia/tap/ask-provider-codex"
  depends_on "roshbhatia/tap/ask-provider-copilot"
  depends_on "roshbhatia/tap/ask-provider-crush"
  depends_on "roshbhatia/tap/ask-provider-cursor"
  depends_on "roshbhatia/tap/ask-provider-devin"
  depends_on "roshbhatia/tap/ask-provider-fx"
  depends_on "roshbhatia/tap/ask-provider-goose"
  depends_on "roshbhatia/tap/ask-provider-hermes"
  depends_on "roshbhatia/tap/ask-provider-opencode"
  depends_on "roshbhatia/tap/ask-provider-pi"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_0.7.1_darwin_arm64.tar.gz"
      sha256 "0ea7dba0248bd5f197f66f0f2f644b7b12577302fe517483f34a932c60112c66"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_0.7.1_linux_arm64.tar.gz"
      sha256 "35f3f49b741bdc57a6a8fd411d3fd55017d4b9bb3417deeec43637a961892a42"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_0.7.1_linux_amd64.tar.gz"
      sha256 "722d07b3ad21b9bf92c85e298f5e4ec557aecb314d70d709c27b34ad31187f40"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      ask
      ask-provider-antigravity
      ask-provider-claude
      ask-provider-codex
      ask-provider-copilot
      ask-provider-crush
      ask-provider-cursor
      ask-provider-devin
      ask-provider-fx
      ask-provider-goose
      ask-provider-hermes
      ask-provider-opencode
      ask-provider-pi
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
