# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderOpencode < Formula
  desc "Opencode CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_opencode_0.8.0_darwin_arm64.tar.gz"
  sha256 "7ef1419c2616284c56c5585229094dd80b5db1b0b100087715fa211349017926"
  license "MIT"

  depends_on "opencode"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_opencode_0.8.0_darwin_arm64.tar.gz"
      sha256 "7ef1419c2616284c56c5585229094dd80b5db1b0b100087715fa211349017926"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_opencode_0.8.0_linux_arm64.tar.gz"
      sha256 "d48703e0989831db5c7c7132cc9f8c6a21f8d14b6c4482006b1a0b712956df99"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_opencode_0.8.0_linux_amd64.tar.gz"
      sha256 "c88fa6060f7922f29dfbc9b4c6c38765c4444c99a311907c226667126b62fee5"
    end
  end

  def install
    bin.install "ask-provider-opencode"
    (share/"ask/providers/opencode").install "share/ask/providers/opencode/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-opencode"
  end
end
