# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderDevin < Formula
  desc "Replay an offline token parser review with devin"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_devin_0.7.1_darwin_arm64.tar.gz"
  sha256 "824316d3deee4ab8414253b45e42bd7593eb3c453047e5286eaf71f4fc3c401b"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_devin_0.7.1_darwin_arm64.tar.gz"
      sha256 "824316d3deee4ab8414253b45e42bd7593eb3c453047e5286eaf71f4fc3c401b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_devin_0.7.1_linux_arm64.tar.gz"
      sha256 "dd7b9640ca8fae212cc6fa340be64d17ed1263fca296e4f7f1d9d6eaa46b10cc"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_devin_0.7.1_linux_amd64.tar.gz"
      sha256 "116139264cd80b5f691cf0495489ac9e2f5a3aad31a8064e5fce72d4daf302e9"
    end
  end

  def install
    bin.install "ask-provider-devin"
    (share/"ask/providers/devin").install "share/ask/providers/devin/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-devin"
  end
end
