# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderGoose < Formula
  desc "Goose CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_goose_0.7.2_darwin_arm64.tar.gz"
  sha256 "96498483c096ee1bc9abfad5996c982df651068abb685c5de32546c312711728"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_goose_0.7.2_darwin_arm64.tar.gz"
      sha256 "96498483c096ee1bc9abfad5996c982df651068abb685c5de32546c312711728"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_goose_0.7.2_linux_arm64.tar.gz"
      sha256 "00eedaf38d6d8966e89918b5eb82d1c9e471af9089aedebdaca0b3340a1500bf"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_goose_0.7.2_linux_amd64.tar.gz"
      sha256 "b93ec62e0ca2ebaea2c99be767893281afd0784becb70a0a43834fd10601dcd2"
    end
  end

  def install
    bin.install "ask-provider-goose"
    (share/"ask/providers/goose").install "share/ask/providers/goose/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-goose"
  end
end
