# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderClaude < Formula
  desc "Replay an offline token parser review with claude"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_claude_0.7.1_darwin_arm64.tar.gz"
  sha256 "c92cb3fcd2c6ed52051d576fb343de076144761378cbfe994eb017a5e7ee995e"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_claude_0.7.1_darwin_arm64.tar.gz"
      sha256 "c92cb3fcd2c6ed52051d576fb343de076144761378cbfe994eb017a5e7ee995e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_claude_0.7.1_linux_arm64.tar.gz"
      sha256 "ef549afacde54c2bf1500733f49b665f6b714e6332c8b39f4e14cca38662750c"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_claude_0.7.1_linux_amd64.tar.gz"
      sha256 "18972940116c5bd78938e3e021dd095fe4955ca2812b1ecc24b8a455873b9f10"
    end
  end

  def install
    bin.install "ask-provider-claude"
    (share/"ask/providers/claude").install "share/ask/providers/claude/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-claude"
  end
end
