# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderAntigravity < Formula
  desc "Replay an offline token parser review with antigravity"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_antigravity_0.7.1_darwin_arm64.tar.gz"
  sha256 "6953dc0ce3ec7f90b9f31b35fa6a650b23461c9f5d2833274252be4da41b4a33"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_antigravity_0.7.1_darwin_arm64.tar.gz"
      sha256 "6953dc0ce3ec7f90b9f31b35fa6a650b23461c9f5d2833274252be4da41b4a33"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_antigravity_0.7.1_linux_arm64.tar.gz"
      sha256 "3fabd3753b2f1526e46fdc875bad8afcb5b1985169d7f054639b4f764078aabe"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_antigravity_0.7.1_linux_amd64.tar.gz"
      sha256 "4c96fbbcacdb6f49ff98d9110a866fda5b6bed85dc2f01ae814026a322fbd292"
    end
  end

  def install
    bin.install "ask-provider-antigravity"
    (share/"ask/providers/antigravity").install "share/ask/providers/antigravity/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-antigravity"
  end
end
