# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderHermes < Formula
  desc "Hermes Agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_hermes_0.7.2_darwin_arm64.tar.gz"
  sha256 "44071a36b7a28765f4e275920b16683987348b7286e76cf20016b11226adfedb"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_hermes_0.7.2_darwin_arm64.tar.gz"
      sha256 "44071a36b7a28765f4e275920b16683987348b7286e76cf20016b11226adfedb"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_hermes_0.7.2_linux_arm64.tar.gz"
      sha256 "cf6b9004bf0b2450622a930e2d1677c75afd341b6ea826391ad811b48fea6b3e"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_hermes_0.7.2_linux_amd64.tar.gz"
      sha256 "ee95b48bdd22035d25f4ff23f8f87e6b85ff645ef709e720978fa89642d55d23"
    end
  end

  def install
    bin.install "ask-provider-hermes"
    (share/"ask/providers/hermes").install "share/ask/providers/hermes/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-hermes"
  end
end
