# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCodex < Formula
  desc "Codex CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_codex_0.8.0_darwin_arm64.tar.gz"
  sha256 "61defaeaf2b1bf9ba6675fbc3efbe58abd40f1202bd36d2cd1712671ecc85b52"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_codex_0.8.0_darwin_arm64.tar.gz"
      sha256 "61defaeaf2b1bf9ba6675fbc3efbe58abd40f1202bd36d2cd1712671ecc85b52"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_codex_0.8.0_linux_arm64.tar.gz"
      sha256 "a64325071474aece5a7660b98919242e526e4941478366dd78e0871472d99759"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_codex_0.8.0_linux_amd64.tar.gz"
      sha256 "0a713949a7d4ca28528146270080b8ddc042b712871523457c2ac79247359092"
    end
  end

  def install
    bin.install "ask-provider-codex"
    (share/"ask/providers/codex").install "share/ask/providers/codex/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-codex"
  end
end
