# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderFx < Formula
  desc "Fx coding agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_fx_0.8.0_darwin_arm64.tar.gz"
  sha256 "2909e13edaa05e74ef565a66ed81a7fd3a0f1fcad1218584409fc5225daa74c7"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_fx_0.8.0_darwin_arm64.tar.gz"
      sha256 "2909e13edaa05e74ef565a66ed81a7fd3a0f1fcad1218584409fc5225daa74c7"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_fx_0.8.0_linux_arm64.tar.gz"
      sha256 "ecbe7d6ab701d744c4e6e5164aa3cee9f2d0362bf17e1698bdc80c2be9c41aca"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_fx_0.8.0_linux_amd64.tar.gz"
      sha256 "096147a9e522f125cdc2b9b069d34a114ffc7799ecf6b82b4e791bf82bd69db2"
    end
  end

  def install
    bin.install "ask-provider-fx"
    (share/"ask/providers/fx").install "share/ask/providers/fx/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-fx"
  end
end
