# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskAll < Formula
  desc "All providers for ask"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_0.8.0_darwin_arm64.tar.gz"
  sha256 "20ec415547720ef8e943d9c05f54b7e05779b80fb4c7ed3a2d298ff626b0ce43"
  license "MIT"

  depends_on "roshbhatia/tap/ask"
  depends_on "roshbhatia/tap/ask-provider-antigravity"
  depends_on "roshbhatia/tap/ask-provider-claude"
  depends_on "roshbhatia/tap/ask-provider-codex"
  depends_on "roshbhatia/tap/ask-provider-copilot"
  depends_on "roshbhatia/tap/ask-provider-crush"
  depends_on "roshbhatia/tap/ask-provider-cursor"
  depends_on "roshbhatia/tap/ask-provider-devin"
  depends_on "roshbhatia/tap/ask-provider-fx"
  depends_on "roshbhatia/tap/ask-provider-goose"
  depends_on "roshbhatia/tap/ask-provider-hermes"
  depends_on "roshbhatia/tap/ask-provider-opencode"
  depends_on "roshbhatia/tap/ask-provider-pi"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_0.8.0_darwin_arm64.tar.gz"
      sha256 "20ec415547720ef8e943d9c05f54b7e05779b80fb4c7ed3a2d298ff626b0ce43"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_0.8.0_linux_arm64.tar.gz"
      sha256 "9e54c4120c34cc0ed878a66ea53242dbd41692973ebd96eb79340fcd9325ed3c"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_0.8.0_linux_amd64.tar.gz"
      sha256 "6c68a44156cf3711318bcfd450b216b441ccf81f98f446d756c0673c0490c284"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      ask
      ask-provider-antigravity
      ask-provider-claude
      ask-provider-codex
      ask-provider-copilot
      ask-provider-crush
      ask-provider-cursor
      ask-provider-devin
      ask-provider-fx
      ask-provider-goose
      ask-provider-hermes
      ask-provider-opencode
      ask-provider-pi
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
