# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderPi < Formula
  desc "Replay an offline token parser review with pi"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_pi_0.7.1_darwin_arm64.tar.gz"
  sha256 "3653333907062d9db13b32bb30cfdc1edf4ab6c13753eeb1c36ffbe1392388cd"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_pi_0.7.1_darwin_arm64.tar.gz"
      sha256 "3653333907062d9db13b32bb30cfdc1edf4ab6c13753eeb1c36ffbe1392388cd"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_pi_0.7.1_linux_arm64.tar.gz"
      sha256 "04d95b35f4deec7b664100baa1e75e0eae85330e49f360b26a869c73017a6fe6"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_pi_0.7.1_linux_amd64.tar.gz"
      sha256 "e130fc046e44dee740ac13e1e30dc4a1163f478aa5a1216192c3e1ae24387727"
    end
  end

  def install
    bin.install "ask-provider-pi"
    (share/"ask/providers/pi").install "share/ask/providers/pi/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-pi"
  end
end
