# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderPi < Formula
  desc "Pi coding agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_pi_0.7.2_darwin_arm64.tar.gz"
  sha256 "8713b2516fd58c1ae91681504077a21047fe29d2d3800dffbe92b3e76b9fcf5c"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_pi_0.7.2_darwin_arm64.tar.gz"
      sha256 "8713b2516fd58c1ae91681504077a21047fe29d2d3800dffbe92b3e76b9fcf5c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_pi_0.7.2_linux_arm64.tar.gz"
      sha256 "66eeee04929fb5da2c1baa3eb83f6b85b42d267f2812c32695b873d3d9ff59d5"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_pi_0.7.2_linux_amd64.tar.gz"
      sha256 "37a8e363e1518173116bf54c33cebdd51023f1eb2e7cbb60cf7018f9dcde9345"
    end
  end

  def install
    bin.install "ask-provider-pi"
    (share/"ask/providers/pi").install "share/ask/providers/pi/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-pi"
  end
end
