# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCrush < Formula
  desc "Crush CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_crush_0.7.2_darwin_arm64.tar.gz"
  sha256 "4f88187361f77fc90f6bbdfcdfec457cffafa53dd9d6161b0912fa8c8431de00"
  license "MIT"

  depends_on "charmbracelet/tap/crush"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_crush_0.7.2_darwin_arm64.tar.gz"
      sha256 "4f88187361f77fc90f6bbdfcdfec457cffafa53dd9d6161b0912fa8c8431de00"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_crush_0.7.2_linux_arm64.tar.gz"
      sha256 "e446f66c6e7f96270a9b1ae2b9fdf07cfea5b9b974397f13bed3e88a2a62c1bf"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_crush_0.7.2_linux_amd64.tar.gz"
      sha256 "585f5a43ebae5ce97b4de34e56a868d522bee34d4ab19cf8ca14ca912ff0b35d"
    end
  end

  def install
    bin.install "ask-provider-crush"
    (share/"ask/providers/crush").install "share/ask/providers/crush/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-crush"
  end
end
