# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderClaude < Formula
  desc "Claude Code"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_claude_0.7.2_darwin_arm64.tar.gz"
  sha256 "4c2ad33cad6e385e8433655324b20d76b5caec236050e414cb3e46f83a18ab0c"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_claude_0.7.2_darwin_arm64.tar.gz"
      sha256 "4c2ad33cad6e385e8433655324b20d76b5caec236050e414cb3e46f83a18ab0c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_claude_0.7.2_linux_arm64.tar.gz"
      sha256 "3e828a83c9092e1c5c8d86ac1793eb26c0b4996c915c43b2b281dd6f9294b951"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_claude_0.7.2_linux_amd64.tar.gz"
      sha256 "13cebdac74a45910a58d630402acfd425aca2613f1518b05015ef96b90157b0c"
    end
  end

  def install
    bin.install "ask-provider-claude"
    (share/"ask/providers/claude").install "share/ask/providers/claude/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-claude"
  end
end
