# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCursor < Formula
  desc "Cursor Agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_cursor_0.7.2_darwin_arm64.tar.gz"
  sha256 "cc8646ac148df1d1ef0ee1c109224604448614c2c8e33645dcc6afa22fa53300"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_cursor_0.7.2_darwin_arm64.tar.gz"
      sha256 "cc8646ac148df1d1ef0ee1c109224604448614c2c8e33645dcc6afa22fa53300"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_cursor_0.7.2_linux_arm64.tar.gz"
      sha256 "95a0caf4b399ac3fad2b0ea01b9ba74d4d69f30e808561c42041928dd927d863"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_cursor_0.7.2_linux_amd64.tar.gz"
      sha256 "216a309087b75405843ebcb5419b75ea245070c9455823b921e4c5978e5df2e2"
    end
  end

  def install
    bin.install "ask-provider-cursor"
    (share/"ask/providers/cursor").install "share/ask/providers/cursor/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-cursor"
  end
end
