# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderOpencode < Formula
  desc "Replay an offline token parser review with opencode"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_opencode_0.7.1_darwin_arm64.tar.gz"
  sha256 "8c582fec002c7265b982dc0a9be373e4effa41c7ed97e780dd56f1005b892164"
  license "MIT"

  depends_on "opencode"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_opencode_0.7.1_darwin_arm64.tar.gz"
      sha256 "8c582fec002c7265b982dc0a9be373e4effa41c7ed97e780dd56f1005b892164"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_opencode_0.7.1_linux_arm64.tar.gz"
      sha256 "c2c39e30d20f50a879e327d4176bddf6054f654663d63ff56b6471afe205e2d6"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_opencode_0.7.1_linux_amd64.tar.gz"
      sha256 "bf18a06b32898dd8e954626e9031ef1581d076ee76a0d93a41f9e07fc48032c6"
    end
  end

  def install
    bin.install "ask-provider-opencode"
    (share/"ask/providers/opencode").install "share/ask/providers/opencode/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-opencode"
  end
end
