# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderDevin < Formula
  desc "Devin CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_devin_0.7.2_darwin_arm64.tar.gz"
  sha256 "aa8becaac9937e56adeb4fd5b32e20c79d50aee6519caa7bbb85c3860c2b5f4b"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_devin_0.7.2_darwin_arm64.tar.gz"
      sha256 "aa8becaac9937e56adeb4fd5b32e20c79d50aee6519caa7bbb85c3860c2b5f4b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_devin_0.7.2_linux_arm64.tar.gz"
      sha256 "61f60a3b02aa99db245ac1686f6c6d07e9046b29f9a9532f477670eb3b2f1040"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_devin_0.7.2_linux_amd64.tar.gz"
      sha256 "732f2de18894ecc0cdad4bd2e58bb8fb514e4c66ddd8abff218634fe39d198d2"
    end
  end

  def install
    bin.install "ask-provider-devin"
    (share/"ask/providers/devin").install "share/ask/providers/devin/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-devin"
  end
end
