# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCodex < Formula
  desc "Replay an offline token parser review with codex"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_codex_0.7.1_darwin_arm64.tar.gz"
  sha256 "8df1faeeb13dbd8e14ffa11b55d6ecdc9a3647818b3f0fc3998044803f1dc1fe"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_codex_0.7.1_darwin_arm64.tar.gz"
      sha256 "8df1faeeb13dbd8e14ffa11b55d6ecdc9a3647818b3f0fc3998044803f1dc1fe"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_codex_0.7.1_linux_arm64.tar.gz"
      sha256 "0283ca5ffa3ecfcaf5d0730f86b491e235ed40385dee57f340588ebfba1c84c8"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_codex_0.7.1_linux_amd64.tar.gz"
      sha256 "1f2d58404f6952ab4450546bc996b1f459b8368140a9f703c330a911a5ceea87"
    end
  end

  def install
    bin.install "ask-provider-codex"
    (share/"ask/providers/codex").install "share/ask/providers/codex/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-codex"
  end
end
