# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskAll < Formula
  desc "All providers for ask"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_darwin_arm64.tar.gz"
  sha256 "dd4f798426a97d4cecbaf3a669ce519966a9f90137e43c63ac2b5277b2f9da4a"
  license "MIT"

  depends_on "roshbhatia/tap/ask"
  depends_on "roshbhatia/tap/ask-provider-antigravity"
  depends_on "roshbhatia/tap/ask-provider-claude"
  depends_on "roshbhatia/tap/ask-provider-codex"
  depends_on "roshbhatia/tap/ask-provider-copilot"
  depends_on "roshbhatia/tap/ask-provider-crush"
  depends_on "roshbhatia/tap/ask-provider-cursor"
  depends_on "roshbhatia/tap/ask-provider-devin"
  depends_on "roshbhatia/tap/ask-provider-fx"
  depends_on "roshbhatia/tap/ask-provider-goose"
  depends_on "roshbhatia/tap/ask-provider-hermes"
  depends_on "roshbhatia/tap/ask-provider-opencode"
  depends_on "roshbhatia/tap/ask-provider-pi"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_darwin_arm64.tar.gz"
      sha256 "dd4f798426a97d4cecbaf3a669ce519966a9f90137e43c63ac2b5277b2f9da4a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_linux_arm64.tar.gz"
      sha256 "b10631d9321534193ee56c3892d280c001521636087e3d720eb760acdfbf64a5"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_linux_amd64.tar.gz"
      sha256 "59290630c0006f51d174c936e1252b95124c7830f3186265533c3785d6779b9e"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      ask
      ask-provider-antigravity
      ask-provider-claude
      ask-provider-codex
      ask-provider-copilot
      ask-provider-crush
      ask-provider-cursor
      ask-provider-devin
      ask-provider-fx
      ask-provider-goose
      ask-provider-hermes
      ask-provider-opencode
      ask-provider-pi
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
