# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderFx < Formula
  desc "Fx coding agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_fx_0.7.2_darwin_arm64.tar.gz"
  sha256 "afa3c0c46171c338c9e7feeb6ef97a2805d038a118c5a915dc74b8e42f1773bd"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_fx_0.7.2_darwin_arm64.tar.gz"
      sha256 "afa3c0c46171c338c9e7feeb6ef97a2805d038a118c5a915dc74b8e42f1773bd"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_fx_0.7.2_linux_arm64.tar.gz"
      sha256 "1d76b7d8555798efd8c2fca5e8cb15b8f06ca50455d7838e18935c3a04bee540"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_fx_0.7.2_linux_amd64.tar.gz"
      sha256 "0d6bf8087c546085a5def0a03231be3e39ce793bd29a01b568e35c3c8f3cc3b4"
    end
  end

  def install
    bin.install "ask-provider-fx"
    (share/"ask/providers/fx").install "share/ask/providers/fx/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-fx"
  end
end
