# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderPi < Formula
  desc "Pi coding agent CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_pi_0.8.0_darwin_arm64.tar.gz"
  sha256 "fcd758adae01208d252b388194b015f05d93c3df90dca846410f211d2dd03aa6"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_pi_0.8.0_darwin_arm64.tar.gz"
      sha256 "fcd758adae01208d252b388194b015f05d93c3df90dca846410f211d2dd03aa6"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_pi_0.8.0_linux_arm64.tar.gz"
      sha256 "8ce148c687b825a59ef21877a6e675474514c9923bc474dc2e8da23aa0318671"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_pi_0.8.0_linux_amd64.tar.gz"
      sha256 "ffa428ccfbd66237ebd98b454c3c408a4a60f58130d6e3392acfdd92c40fc267"
    end
  end

  def install
    bin.install "ask-provider-pi"
    (share/"ask/providers/pi").install "share/ask/providers/pi/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-pi"
  end
end
