# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderGoose < Formula
  desc "Goose CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_goose_0.8.0_darwin_arm64.tar.gz"
  sha256 "faba2aebbcd94bcd63fb4793739922e55764cfb113d092e964745878ed1dff68"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_goose_0.8.0_darwin_arm64.tar.gz"
      sha256 "faba2aebbcd94bcd63fb4793739922e55764cfb113d092e964745878ed1dff68"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_goose_0.8.0_linux_arm64.tar.gz"
      sha256 "a0202e4dacf7af106add1d1525fd0e116d68927cc7fdc92f069dcbf2ce6d90d9"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.8.0/ask_provider_goose_0.8.0_linux_amd64.tar.gz"
      sha256 "c9a4fbb5b48e8e3021f4fa93a4b3849d5e8cadc5b99111d7c5d6bc3fd4226993"
    end
  end

  def install
    bin.install "ask-provider-goose"
    (share/"ask/providers/goose").install "share/ask/providers/goose/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-goose"
  end
end
