# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCopilot < Formula
  desc "GitHub Copilot CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_copilot_0.7.2_darwin_arm64.tar.gz"
  sha256 "203dc2b9de1f2bb997ea070bc290abca5d587f36b8446027eb9840c14e45590b"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_copilot_0.7.2_darwin_arm64.tar.gz"
      sha256 "203dc2b9de1f2bb997ea070bc290abca5d587f36b8446027eb9840c14e45590b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_copilot_0.7.2_linux_arm64.tar.gz"
      sha256 "a5a6f79588f0318bb9acb828592982051e4ffc347678d57f11b2d3301f9d60e6"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_copilot_0.7.2_linux_amd64.tar.gz"
      sha256 "3f6f83bb70dd20201b4098196b7e07bf5c5611ae2b3687a73ede783095cfab8f"
    end
  end

  def install
    bin.install "ask-provider-copilot"
    (share/"ask/providers/copilot").install "share/ask/providers/copilot/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-copilot"
  end
end
