# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderFx < Formula
  desc "Replay an offline token parser review with fx"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_fx_0.7.1_darwin_arm64.tar.gz"
  sha256 "2058ae84419ff39f045ea445fa89a9704225f28e3ad304983969d01f498c7a4d"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_fx_0.7.1_darwin_arm64.tar.gz"
      sha256 "2058ae84419ff39f045ea445fa89a9704225f28e3ad304983969d01f498c7a4d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_fx_0.7.1_linux_arm64.tar.gz"
      sha256 "00d29a729e7daf8aa4c2cca1b274971ec84267b82c4de17bfcf686bf68148117"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_fx_0.7.1_linux_amd64.tar.gz"
      sha256 "84a55190a1665a333cf29c431e92f26c78eb747c95b9d59446c9ea25f56e6377"
    end
  end

  def install
    bin.install "ask-provider-fx"
    (share/"ask/providers/fx").install "share/ask/providers/fx/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-fx"
  end
end
