# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderOpencode < Formula
  desc "Opencode CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_opencode_0.7.2_darwin_arm64.tar.gz"
  sha256 "186331a3df4579ef12ee0a3b13cab1bcbb7bc987b7c3061cd53e3cc6f4bfda31"
  license "MIT"

  depends_on "opencode"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_opencode_0.7.2_darwin_arm64.tar.gz"
      sha256 "186331a3df4579ef12ee0a3b13cab1bcbb7bc987b7c3061cd53e3cc6f4bfda31"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_opencode_0.7.2_linux_arm64.tar.gz"
      sha256 "5b8d9ce1133cba435634f6d49df4abbd8e19c243066da63e7ace602eeea76743"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_opencode_0.7.2_linux_amd64.tar.gz"
      sha256 "c9449e5a0f9e601303ab01ce6ecc6943a7afacce27f47e1fb7dbe8555bcd677a"
    end
  end

  def install
    bin.install "ask-provider-opencode"
    (share/"ask/providers/opencode").install "share/ask/providers/opencode/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-opencode"
  end
end
