# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCopilot < Formula
  desc "Replay an offline token parser review with copilot"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_copilot_0.7.1_darwin_arm64.tar.gz"
  sha256 "1e52dbb5e808f56994177072eb5c1f8764649d5aa6de9cd5bb2d21d196f7e958"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_copilot_0.7.1_darwin_arm64.tar.gz"
      sha256 "1e52dbb5e808f56994177072eb5c1f8764649d5aa6de9cd5bb2d21d196f7e958"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_copilot_0.7.1_linux_arm64.tar.gz"
      sha256 "d3b899e787bf911b03c2a2daf3f7e8c7700c8238f56f486e1658ecfccd9e4525"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_copilot_0.7.1_linux_amd64.tar.gz"
      sha256 "32aeab3766a6f9bcbad4c9acdf7b36a836bca3ee520d411041ee1d543f3ff325"
    end
  end

  def install
    bin.install "ask-provider-copilot"
    (share/"ask/providers/copilot").install "share/ask/providers/copilot/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-copilot"
  end
end
