# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCodex < Formula
  desc "Codex CLI"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_codex_0.7.2_darwin_arm64.tar.gz"
  sha256 "553f2bfec693916686e813c579fb67cde61b1fd016bc281d5361b953af3bcfe9"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_codex_0.7.2_darwin_arm64.tar.gz"
      sha256 "553f2bfec693916686e813c579fb67cde61b1fd016bc281d5361b953af3bcfe9"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_codex_0.7.2_linux_arm64.tar.gz"
      sha256 "24cc76ac2489111b74746cde406a50433dfcac1c02e1868533b567fe20001c82"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_provider_codex_0.7.2_linux_amd64.tar.gz"
      sha256 "6d5e52e01fe3b7d01dcc872062f2dec5555aba0bee98b3f8348764e9bb2bbe18"
    end
  end

  def install
    bin.install "ask-provider-codex"
    (share/"ask/providers/codex").install "share/ask/providers/codex/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-codex"
  end
end
