# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderGoose < Formula
  desc "Replay an offline token parser review with goose"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_goose_0.7.1_darwin_arm64.tar.gz"
  sha256 "66561721b4bfc689a8b0ea4835c19cf48402f00ee0fae9bc6b8338e6ec70fba3"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_goose_0.7.1_darwin_arm64.tar.gz"
      sha256 "66561721b4bfc689a8b0ea4835c19cf48402f00ee0fae9bc6b8338e6ec70fba3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_goose_0.7.1_linux_arm64.tar.gz"
      sha256 "64b816d7d32a255809ee080a9b8f5db3930fc462f0ea5296e560c69b4fb2eada"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_goose_0.7.1_linux_amd64.tar.gz"
      sha256 "71349b95c0d6cacdd166b5858318eddb6d019a41de59984bffa225a2026a1209"
    end
  end

  def install
    bin.install "ask-provider-goose"
    (share/"ask/providers/goose").install "share/ask/providers/goose/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-goose"
  end
end
