# This file is generated by hack/update.rb. Edit packages.yml instead.
class AskProviderCursor < Formula
  desc "Replay an offline token parser review with cursor"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_cursor_0.7.1_darwin_arm64.tar.gz"
  sha256 "9d81a2ac27b9759a7521e07e2b0e19f93f13c87141eb9a9b4649e0a94fc7288c"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_cursor_0.7.1_darwin_arm64.tar.gz"
      sha256 "9d81a2ac27b9759a7521e07e2b0e19f93f13c87141eb9a9b4649e0a94fc7288c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_cursor_0.7.1_linux_arm64.tar.gz"
      sha256 "de03f687bc1231ee6d0eabd3e93d0280e4578ebe0cf5148300e0a7bba404a1d7"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.1/ask_provider_cursor_0.7.1_linux_amd64.tar.gz"
      sha256 "4e7bec7406c719c07fddd6df3dbded3555147f010c5261a18d1d76c045511631"
    end
  end

  def install
    bin.install "ask-provider-cursor"
    (share/"ask/providers/cursor").install "share/ask/providers/cursor/provider.yaml"
  end

  test do
    assert_path_exists bin/"ask-provider-cursor"
  end
end
