# This file is generated by hack/update.rb. Edit packages.yml instead.
class Ask < Formula
  desc "Query agent harnesses through provider-defined adapters"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.0/ask_0.7.0_darwin_arm64.tar.gz"
  sha256 "058240d8e51c841d02d285a02b5b2724623247821d5b8492b1221d098a449c3b"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.0/ask_0.7.0_darwin_arm64.tar.gz"
      sha256 "058240d8e51c841d02d285a02b5b2724623247821d5b8492b1221d098a449c3b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.0/ask_0.7.0_linux_arm64.tar.gz"
      sha256 "4f1512cd0986594a430385faf574316bc0d07e4756ef158d076fb397c8b2f5b9"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.0/ask_0.7.0_linux_amd64.tar.gz"
      sha256 "a4c6453b68e4c30c1b13ca33681628aee18de4dd120c21bad6ad65fed9ea45e9"
    end
  end

  def install
    libexec.install "ask"
    generate_completions_from_executable(libexec/"ask", "completion")
    nu_completion = buildpath/"ask.nu"
    nu_completion.write Utils.safe_popen_read(libexec/"ask", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
    (bin/"ask").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/ask" "$@"
    SH
    (bin/"ask").chmod 0755
  end

  test do
    assert_match "ask", shell_output("#{bin}/ask --help 2>&1")
  end
end
