# This file is generated by hack/update.rb. Edit packages.yml instead.
class Ask < Formula
  desc "Query agent harnesses through provider-defined adapters"
  homepage "https://github.com/roshbhatia/ask"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.5.0/ask_0.5.0_darwin_arm64.tar.gz"
      sha256 "0feffc6768ed5365021b60ef18d6434079951590a158573125097d88c8cece85"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.5.0/ask_0.5.0_darwin_amd64.tar.gz"
      sha256 "df37cf5dc16d12e66401a8e24b84ececc89afa6ff13c83d32c31c6a85372e835"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.5.0/ask_0.5.0_linux_arm64.tar.gz"
      sha256 "e4043835bf97cdc92827d40b884c959b78706a5e4b9ed9b4bdc7fb741ac54950"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.5.0/ask_0.5.0_linux_amd64.tar.gz"
      sha256 "6f2fee5a1c4890826d15f9a7f61182eb7ac293d82e913e7a10aa90f5c8950794"
    end
  end

  def install
    bin.install "ask"
    generate_completions_from_executable(bin/"ask", "completion")
    nu_completion = buildpath/"ask.nu"
    nu_completion.write Utils.safe_popen_read(bin/"ask", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "ask", shell_output("#{bin}/ask --help")
  end
end
