# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class Ask < Formula
  desc "Query agent harnesses through provider-defined adapters"
  homepage "https://github.com/roshbhatia/ask"
  url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_darwin_arm64.tar.gz"
  sha256 "dd4f798426a97d4cecbaf3a669ce519966a9f90137e43c63ac2b5277b2f9da4a"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_darwin_arm64.tar.gz"
      sha256 "dd4f798426a97d4cecbaf3a669ce519966a9f90137e43c63ac2b5277b2f9da4a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_linux_arm64.tar.gz"
      sha256 "b10631d9321534193ee56c3892d280c001521636087e3d720eb760acdfbf64a5"
    end
    on_intel do
      url "https://github.com/roshbhatia/ask/releases/download/v0.7.2/ask_0.7.2_linux_amd64.tar.gz"
      sha256 "59290630c0006f51d174c936e1252b95124c7830f3186265533c3785d6779b9e"
    end
  end

  def install
    libexec.install "ask"
    generate_completions_from_executable(libexec/"ask", "completion")
    nu_completion = buildpath/"ask.nu"
    nu_completion.write Utils.safe_popen_read(libexec/"ask", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
    (bin/"ask").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/ask" "$@"
    SH
    (bin/"ask").chmod 0755
  end

  test do
    assert_match "ask", shell_output("#{bin}/ask --help 2>&1")
  end
end
