# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderLocalNotes < Formula
  desc "Keep a local note on prefix validation"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_local-notes_0.12.3_darwin_arm64.tar.gz"
  sha256 "56c4829c977ce45588d5229674d3929ab9e6ed3e0bb639b4614df376d4fc4047"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_local-notes_0.12.3_darwin_arm64.tar.gz"
      sha256 "56c4829c977ce45588d5229674d3929ab9e6ed3e0bb639b4614df376d4fc4047"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_local-notes_0.12.3_linux_arm64.tar.gz"
      sha256 "4cce099ef80e412d8afddf41b4c2e8d322076fd9811884ab33fbc31ab165d954"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_local-notes_0.12.3_linux_amd64.tar.gz"
      sha256 "f33bc4e6f188f839961f8da7d7b51e363dbce79b106d0f2da0e7b92496e1d9d7"
    end
  end

  def install
    bin.install "changes-provider-local-notes"
    (share/"changes/providers/local-notes").install "share/changes/providers/local-notes/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-local-notes"
  end
end
