# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderGithubPr < Formula
  desc "Replay an offline pull request review thread"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_github-pr_0.12.3_darwin_arm64.tar.gz"
  sha256 "1881259c4eca5bb38e4595e61dacea0a0c6642e8d480c26e5e3debbdaa82bf52"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_github-pr_0.12.3_darwin_arm64.tar.gz"
      sha256 "1881259c4eca5bb38e4595e61dacea0a0c6642e8d480c26e5e3debbdaa82bf52"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_github-pr_0.12.3_linux_arm64.tar.gz"
      sha256 "4393b8a5648ccb1608915be4f20880a206419cb433f32c7cde7df9831d1e34c7"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_github-pr_0.12.3_linux_amd64.tar.gz"
      sha256 "19cff32743a5262a97e629ed1e1e5ecee7441494813738c0d9103c4bbadaa6b5"
    end
  end

  def install
    bin.install "changes-provider-github-pr"
    (share/"changes/providers/github-pr").install "share/changes/providers/github-pr/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-github-pr"
  end
end
