# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderGitNotes < Formula
  desc "Store token parser review notes in Git"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_git-notes_0.12.3_darwin_arm64.tar.gz"
  sha256 "2aabe1312bcc222bc1c29e785b8526db146cfae8b35b55c5a4f8cce6e8f99ee5"
  license "MIT"

  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_git-notes_0.12.3_darwin_arm64.tar.gz"
      sha256 "2aabe1312bcc222bc1c29e785b8526db146cfae8b35b55c5a4f8cce6e8f99ee5"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_git-notes_0.12.3_linux_arm64.tar.gz"
      sha256 "c8c194fed17be857104bfb641c56969faad78546b36c1b0f14a535528212bafb"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_git-notes_0.12.3_linux_amd64.tar.gz"
      sha256 "cdfa401667f818448f5ef667df35a0cc663d3e50f8343898c0b70276532a186c"
    end
  end

  def install
    bin.install "changes-provider-git-notes"
    (share/"changes/providers/git-notes").install "share/changes/providers/git-notes/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-git-notes"
  end
end
