# This file is generated by hack/update.rb. Edit packages.yml instead.
class Changes < Formula
  desc "Review Git changes with symbol and call context"
  homepage "https://github.com/roshbhatia/changes"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.8.0/changes_0.8.0_darwin_arm64.tar.gz"
      sha256 "7a5722a5440c8fd54d7529487fd68080e989eea7574d354edd5a183932cfaac5"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.8.0/changes_0.8.0_darwin_amd64.tar.gz"
      sha256 "1a3b0de183df74bb0e552407cade8b6b8ece8cb51ecf77043ee1c89cf2412c7b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.8.0/changes_0.8.0_linux_arm64.tar.gz"
      sha256 "64c726243f1b457de9ea6fc55ff138376c98e7c38bee927a1d1c0f63048b8c68"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.8.0/changes_0.8.0_linux_amd64.tar.gz"
      sha256 "0a83c00463169f460ff7245805ae543083ca606b15b2c3a35dc3c4eff0572d2c"
    end
  end

  def install
    bin.install "changes"
    generate_completions_from_executable(bin/"changes", "completion")
    nu_completion = buildpath/"changes.nu"
    nu_completion.write Utils.safe_popen_read(bin/"changes", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "changes", shell_output("#{bin}/changes --help")
  end
end
