# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderCodexReview < Formula
  desc "Replay an offline token parser review"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_codex-review_0.12.3_darwin_arm64.tar.gz"
  sha256 "4bdd6387de4c7b7d9c276652f3f776d2d64913cbc6bab636dbd3a080238b5ab0"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_codex-review_0.12.3_darwin_arm64.tar.gz"
      sha256 "4bdd6387de4c7b7d9c276652f3f776d2d64913cbc6bab636dbd3a080238b5ab0"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_codex-review_0.12.3_linux_arm64.tar.gz"
      sha256 "f778e13d71aad93a78500c228f3532776e791e127049f94b157e1d7e08247726"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_codex-review_0.12.3_linux_amd64.tar.gz"
      sha256 "d47712df9b2114955c4057c323d6e8b9b095ba8575e6f9d32401916ff5b4d310"
    end
  end

  def install
    bin.install "changes-provider-codex-review"
    (share/"changes/providers/codex-review").install "share/changes/providers/codex-review/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-codex-review"
  end
end
