# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesAll < Formula
  desc "All providers for changes"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_0.12.3_darwin_arm64.tar.gz"
  sha256 "fa6d71cc5a70dabfef561e6c6e37fd922e88204735ae517eb600f970f64d34ce"
  license "MIT"

  depends_on "roshbhatia/tap/changes"
  depends_on "roshbhatia/tap/changes-provider-ast-grep"
  depends_on "roshbhatia/tap/changes-provider-calldiff"
  depends_on "roshbhatia/tap/changes-provider-codex-review"
  depends_on "roshbhatia/tap/changes-provider-git-notes"
  depends_on "roshbhatia/tap/changes-provider-github-pr"
  depends_on "roshbhatia/tap/changes-provider-local-notes"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_0.12.3_darwin_arm64.tar.gz"
      sha256 "fa6d71cc5a70dabfef561e6c6e37fd922e88204735ae517eb600f970f64d34ce"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_0.12.3_linux_arm64.tar.gz"
      sha256 "e89f47dc27183bcde43417a8a31634e00a9bf5dfe47d1ca0dc1e53f810c14741"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_0.12.3_linux_amd64.tar.gz"
      sha256 "123c134c4bde1b978d695f1558b1d1644ce29f6237db02b80166db2b87975eb9"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      changes
      changes-provider-ast-grep
      changes-provider-calldiff
      changes-provider-codex-review
      changes-provider-git-notes
      changes-provider-github-pr
      changes-provider-local-notes
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
