# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderAstGrep < Formula
  desc "Inspect the changed token parser symbol"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_ast-grep_0.13.0_darwin_arm64.tar.gz"
  sha256 "e787382c19c8a1a9d6272cbe8b990a852826abbb895e84eaa5a6bd8125a8c7b8"
  license "MIT"

  depends_on "ast-grep"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_ast-grep_0.13.0_darwin_arm64.tar.gz"
      sha256 "e787382c19c8a1a9d6272cbe8b990a852826abbb895e84eaa5a6bd8125a8c7b8"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_ast-grep_0.13.0_linux_arm64.tar.gz"
      sha256 "e9d9963cb51d56f8d34f9e54a72450c31a0eea269b366b094d4e6f25911bb07b"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_ast-grep_0.13.0_linux_amd64.tar.gz"
      sha256 "37193eb57d95aea5e3d791be5921ce1018f77a56f4bcecc09c3e1adfce3240d0"
    end
  end

  def install
    bin.install "changes-provider-ast-grep"
    (share/"changes/providers/ast-grep").install "share/changes/providers/ast-grep/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-ast-grep"
  end
end
