# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderAstGrep < Formula
  desc "Inspect the changed token parser symbol"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_ast-grep_0.12.3_darwin_arm64.tar.gz"
  sha256 "5318dcdf3c0a37736c284e6d1c811a87de090e024a95facae44f5429f409849f"
  license "MIT"

  depends_on "ast-grep"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_ast-grep_0.12.3_darwin_arm64.tar.gz"
      sha256 "5318dcdf3c0a37736c284e6d1c811a87de090e024a95facae44f5429f409849f"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_ast-grep_0.12.3_linux_arm64.tar.gz"
      sha256 "a395d5d8cb5688ed488b1a819224c08ae58ab8390ab679b1d98d6bb35b3759ca"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_ast-grep_0.12.3_linux_amd64.tar.gz"
      sha256 "fd3dcdd3996a9c004f615173d04f1b71fc3551e847eb71c2b523501495f19f46"
    end
  end

  def install
    bin.install "changes-provider-ast-grep"
    (share/"changes/providers/ast-grep").install "share/changes/providers/ast-grep/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-ast-grep"
  end
end
