# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderCalldiff < Formula
  desc "Inspect the new validation call"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_calldiff_0.12.3_darwin_arm64.tar.gz"
  sha256 "d66cf63df091db97c11893ee34d6cbc254d8761ee18e297610aa473c58cda89d"
  license "MIT"

  depends_on "git"
  depends_on "node"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_calldiff_0.12.3_darwin_arm64.tar.gz"
      sha256 "d66cf63df091db97c11893ee34d6cbc254d8761ee18e297610aa473c58cda89d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_calldiff_0.12.3_linux_arm64.tar.gz"
      sha256 "7f7be66c5b65ef4e48c952bf8a753a32817e014a4f31ea8db05d5d17fb6ab164"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.12.3/changes_provider_calldiff_0.12.3_linux_amd64.tar.gz"
      sha256 "307fa5a7715478d6f43cb259ed66d20f971478fc340378278abaaac57809ee91"
    end
  end

  def install
    libexec.install "changes-provider-calldiff"
    (share/"changes/providers/calldiff").install "share/changes/providers/calldiff/provider.yaml"
    (libexec/"runtime").install "runtime/package.json", "runtime/package-lock.json"
    system "npm", "ci", "--prefix", libexec/"runtime", "--legacy-peer-deps"
    inreplace libexec/"runtime/node_modules/calldiff/dist/languages/bash.js",
              '[".sh", ".bash"]', '[".sh", ".bash", ".zsh"]'
    (bin/"changes-provider-calldiff").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{libexec}/runtime/node_modules/.bin:$PATH"
      exec "#{libexec}/changes-provider-calldiff" "$@"
    SH
    (bin/"changes-provider-calldiff").chmod 0755
  end

  test do
    assert_path_exists bin/"changes-provider-calldiff"
  end
end
