# This file is generated by hack/update.rb. Edit packages.yml instead.
class Changes < Formula
  desc "Review Git changes with symbol and call context"
  homepage "https://github.com/roshbhatia/changes"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.10.0/changes_0.10.0_darwin_arm64.tar.gz"
      sha256 "21cd3d5333c9de991710a3a0aff40bbc1e4b80311da76222cc0745c61d43a084"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.10.0/changes_0.10.0_darwin_amd64.tar.gz"
      sha256 "064bdeade51b6a2af01b797a4ddca32d63a6b04e23867d03a3c732949471b177"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.10.0/changes_0.10.0_linux_arm64.tar.gz"
      sha256 "cca265d60bbcd1a17659bcf72bed9be01a970726f06c8d1c5f813ba8944d8be9"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.10.0/changes_0.10.0_linux_amd64.tar.gz"
      sha256 "6627facca7837653f83239d0cd3a0d67270835088aa51adb1349205c295a631e"
    end
  end

  def install
    bin.install "changes"
    generate_completions_from_executable(bin/"changes", "completion")
    nu_completion = buildpath/"changes.nu"
    nu_completion.write Utils.safe_popen_read(bin/"changes", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "changes", shell_output("#{bin}/changes --help")
  end
end
