# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderGitNotes < Formula
  desc "Store token parser review notes in Git"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_git-notes_0.13.0_darwin_arm64.tar.gz"
  sha256 "aac6cb69c51d012fdd1853802df93fe3a44277851273cfeee88abc806de6395a"
  license "MIT"

  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_git-notes_0.13.0_darwin_arm64.tar.gz"
      sha256 "aac6cb69c51d012fdd1853802df93fe3a44277851273cfeee88abc806de6395a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_git-notes_0.13.0_linux_arm64.tar.gz"
      sha256 "8ee1c358690774fd3616498c1a9a2989af7f496feaf334d9752f8f89722502f7"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_git-notes_0.13.0_linux_amd64.tar.gz"
      sha256 "f572c10232d97d06d6331a28730bfcc9fc3d1ea8ddb6f28f980292d93a2d1678"
    end
  end

  def install
    bin.install "changes-provider-git-notes"
    (share/"changes/providers/git-notes").install "share/changes/providers/git-notes/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-git-notes"
  end
end
