# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderGithubPr < Formula
  desc "Replay an offline pull request review thread"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_github-pr_0.13.0_darwin_arm64.tar.gz"
  sha256 "dc1b478788cf22dbaafdfaa9609ab9584870faa5c4a7382886b59b397926b000"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_github-pr_0.13.0_darwin_arm64.tar.gz"
      sha256 "dc1b478788cf22dbaafdfaa9609ab9584870faa5c4a7382886b59b397926b000"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_github-pr_0.13.0_linux_arm64.tar.gz"
      sha256 "0b98fbebf4c21ac6ca59bcbe815f07eb0543a1db9e062ff6029098527a906c3f"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_github-pr_0.13.0_linux_amd64.tar.gz"
      sha256 "5719e89105183eff6e5b758983505c0f016ef65bd0c66f60e6e01775c7cae5a4"
    end
  end

  def install
    bin.install "changes-provider-github-pr"
    (share/"changes/providers/github-pr").install "share/changes/providers/github-pr/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-github-pr"
  end
end
