# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesAll < Formula
  desc "All providers for changes"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_0.13.0_darwin_arm64.tar.gz"
  sha256 "b96b608b57c8f77cdfaf8821bc8791e8f619eefce8b9a2536de6427e03d16c0e"
  license "MIT"

  depends_on "roshbhatia/tap/changes"
  depends_on "roshbhatia/tap/changes-provider-ast-grep"
  depends_on "roshbhatia/tap/changes-provider-calldiff"
  depends_on "roshbhatia/tap/changes-provider-codex-review"
  depends_on "roshbhatia/tap/changes-provider-git-notes"
  depends_on "roshbhatia/tap/changes-provider-github-pr"
  depends_on "roshbhatia/tap/changes-provider-local-notes"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_0.13.0_darwin_arm64.tar.gz"
      sha256 "b96b608b57c8f77cdfaf8821bc8791e8f619eefce8b9a2536de6427e03d16c0e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_0.13.0_linux_arm64.tar.gz"
      sha256 "1ac0368c6e16f4e9850154a48edfd1e4e624a0dcd097092b945ec7cd422fd5c7"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_0.13.0_linux_amd64.tar.gz"
      sha256 "c8200f4ddf2d4e93e321563dcbf996b40192370faf9d6c0f2d1351a2b3783654"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      changes
      changes-provider-ast-grep
      changes-provider-calldiff
      changes-provider-codex-review
      changes-provider-git-notes
      changes-provider-github-pr
      changes-provider-local-notes
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
