# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class ChangesProviderCodexReview < Formula
  desc "Replay an offline token parser review"
  homepage "https://github.com/roshbhatia/changes"
  url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_codex-review_0.13.0_darwin_arm64.tar.gz"
  sha256 "2b601c9c06f30610cbb3a22366a120eb0abe2f73a4cc5801e4fa194f17e1b995"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_codex-review_0.13.0_darwin_arm64.tar.gz"
      sha256 "2b601c9c06f30610cbb3a22366a120eb0abe2f73a4cc5801e4fa194f17e1b995"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_codex-review_0.13.0_linux_arm64.tar.gz"
      sha256 "e0f9b8ba6ee1434b19bf417f7f4ac8ff057d58be308183a7042c3e2afe01ec56"
    end
    on_intel do
      url "https://github.com/roshbhatia/changes/releases/download/v0.13.0/changes_provider_codex-review_0.13.0_linux_amd64.tar.gz"
      sha256 "d6eddc36f5680e1af734ed7ed0c2854d0a88b88a490d279ec42dfcde70625f17"
    end
  end

  def install
    bin.install "changes-provider-codex-review"
    (share/"changes/providers/codex-review").install "share/changes/providers/codex-review/provider.yaml"
  end

  test do
    assert_path_exists bin/"changes-provider-codex-review"
  end
end
