# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderEditEvent < Formula
  desc "Record the token parser change for the editor"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_edit-event_0.5.0_darwin_arm64.tar.gz"
  sha256 "52694dfdd8f5c8d6e9e057fd2da17077f9d6d9e32ffc7296d4d1539dc72660e2"
  license "MIT"

  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_edit-event_0.5.0_darwin_arm64.tar.gz"
      sha256 "52694dfdd8f5c8d6e9e057fd2da17077f9d6d9e32ffc7296d4d1539dc72660e2"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_edit-event_0.5.0_linux_arm64.tar.gz"
      sha256 "0ac48cc38de6ecca797afbb2cb3a02c1deb9e6847176e7a9d586b99ea37e7ac1"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_edit-event_0.5.0_linux_amd64.tar.gz"
      sha256 "6f19e71d45ebd39d0789f9987997edefd678668288bd8dc964a697fad8f800a3"
    end
  end

  def install
    bin.install "gate-provider-edit-event"
    (share/"gate/providers").install "share/gate/providers/edit-event.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-edit-event"
  end
end
