# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderBashGuard < Formula
  desc "Read a large token parser with bounded output"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_bash-guard_0.5.0_darwin_arm64.tar.gz"
  sha256 "129caeeda157946b4b6ba5e99a48fd9c4575ba9785ae78ae94a3dd37ed34939f"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_bash-guard_0.5.0_darwin_arm64.tar.gz"
      sha256 "129caeeda157946b4b6ba5e99a48fd9c4575ba9785ae78ae94a3dd37ed34939f"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_bash-guard_0.5.0_linux_arm64.tar.gz"
      sha256 "a52679ee43def6aceec6f5b2fc176527e511776ae9d1a04f4952556e70a91161"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_bash-guard_0.5.0_linux_amd64.tar.gz"
      sha256 "135858e4e54ed8cf6e7c5dfe8cc4a17e24edfcbdcbde8274a36fe1292309a0e9"
    end
  end

  def install
    bin.install "gate-provider-bash-guard"
    (share/"gate/providers").install "share/gate/providers/bash-guard.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-bash-guard"
  end
end
