# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderLoopGate < Formula
  desc "Keep a repair task active until its tests pass"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_loop-gate_0.5.0_darwin_arm64.tar.gz"
  sha256 "08bf0ec562afbc791ebec6abf17d6085799ffe3e98da4fed4f0fa53906d28d71"
  license "MIT"

  depends_on "bash"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_loop-gate_0.5.0_darwin_arm64.tar.gz"
      sha256 "08bf0ec562afbc791ebec6abf17d6085799ffe3e98da4fed4f0fa53906d28d71"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_loop-gate_0.5.0_linux_arm64.tar.gz"
      sha256 "c5ddb93908f116b584a5fcd034bf8e9cbb4aaee07d72e01e090896ef5677d723"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_loop-gate_0.5.0_linux_amd64.tar.gz"
      sha256 "26de6b61a7c3d267d1ce721f879844f2c22c65bae47e6750b56463499d212134"
    end
  end

  def install
    bin.install "gate-provider-loop-gate"
    (share/"gate/providers").install "share/gate/providers/loop-gate.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-loop-gate"
  end
end
