# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateAll < Formula
  desc "All providers for gate"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_darwin_arm64.tar.gz"
  sha256 "721288c7e29cf65bce10d36725b146e53d42a8aa4635f276aa738cce72fec6e3"
  license "MIT"

  depends_on "roshbhatia/tap/gate"
  depends_on "roshbhatia/tap/gate-provider-bash-guard"
  depends_on "roshbhatia/tap/gate-provider-edit-event"
  depends_on "roshbhatia/tap/gate-provider-lint-gate"
  depends_on "roshbhatia/tap/gate-provider-loop-gate"
  depends_on "roshbhatia/tap/gate-provider-nix-guard"
  depends_on "roshbhatia/tap/gate-provider-notes"
  depends_on "roshbhatia/tap/gate-provider-prose-gate"
  depends_on "roshbhatia/tap/gate-provider-read-router"
  depends_on "roshbhatia/tap/gate-provider-review-gate"
  depends_on "roshbhatia/tap/gate-review"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_darwin_arm64.tar.gz"
      sha256 "721288c7e29cf65bce10d36725b146e53d42a8aa4635f276aa738cce72fec6e3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_linux_arm64.tar.gz"
      sha256 "eb6fbf3bb0ddbc2e0159c1a86ec06241242a6f0a8b8b27e156d581f8c92aa6f5"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_linux_amd64.tar.gz"
      sha256 "ec20f0461497c897f645c0228e4f14f2f8f260c57c73ac593c1b493b8c65278e"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      gate
      gate-provider-bash-guard
      gate-provider-edit-event
      gate-provider-lint-gate
      gate-provider-loop-gate
      gate-provider-nix-guard
      gate-provider-notes
      gate-provider-prose-gate
      gate-provider-read-router
      gate-review
      gate-provider-review-gate
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
