# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderLintGate < Formula
  desc "Check token parser formatting after an edit"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_lint-gate_0.5.0_darwin_arm64.tar.gz"
  sha256 "ebc076c12c2a99ff74422c43676dadf282cc6af230dab8f93795fe4ba34b8912"
  license "MIT"

  depends_on "statix"
  depends_on "ruff"
  depends_on "shellcheck"
  depends_on "stylua"
  depends_on "taplo"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_lint-gate_0.5.0_darwin_arm64.tar.gz"
      sha256 "ebc076c12c2a99ff74422c43676dadf282cc6af230dab8f93795fe4ba34b8912"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_lint-gate_0.5.0_linux_arm64.tar.gz"
      sha256 "17cea84b69fe5276b2e1e6252aaa0859181f072d9130e032bd246f8a8d22c703"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_lint-gate_0.5.0_linux_amd64.tar.gz"
      sha256 "49a0b0a9ed50628fe29d343f360ccbb5f016c4fa7105916fdebc2d78365d9cf4"
    end
  end

  def install
    bin.install "gate-provider-lint-gate"
    (share/"gate/providers").install "share/gate/providers/lint-gate.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-lint-gate"
  end
end
