# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderReadRouter < Formula
  desc "Select the token parser lines needed for review"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_read-router_0.5.0_darwin_arm64.tar.gz"
  sha256 "d015f657f2932082bd10d2f6aff7bf9e968d27a390a3e172737794255a2b5a05"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_read-router_0.5.0_darwin_arm64.tar.gz"
      sha256 "d015f657f2932082bd10d2f6aff7bf9e968d27a390a3e172737794255a2b5a05"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_read-router_0.5.0_linux_arm64.tar.gz"
      sha256 "47558d73e5aafb798d9fabecd1a62aa51704e2dafa3c8456678720fb3b444b64"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_read-router_0.5.0_linux_amd64.tar.gz"
      sha256 "e366c0f599e40f9ce1104926c38153d8bce6597dadb709efd52af6e48868da8d"
    end
  end

  def install
    bin.install "gate-provider-read-router"
    (share/"gate/providers").install "share/gate/providers/read-router.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-read-router"
  end
end
