# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderReviewGate < Formula
  desc "Require a review ledger before the critic starts"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_review-gate_0.5.0_darwin_arm64.tar.gz"
  sha256 "2d3de04a4f951d6b802d793cbe4d229d15c64f480a6da8d43edb0c66063dd4f1"
  license "MIT"

  depends_on "roshbhatia/tap/gate-review"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_review-gate_0.5.0_darwin_arm64.tar.gz"
      sha256 "2d3de04a4f951d6b802d793cbe4d229d15c64f480a6da8d43edb0c66063dd4f1"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_review-gate_0.5.0_linux_arm64.tar.gz"
      sha256 "eebf84e825bb472773cb664681b99c96238c088bf2b86952e550f1bd1858e26a"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_review-gate_0.5.0_linux_amd64.tar.gz"
      sha256 "c062bdd63b37b07d23e6b71fb6c0628dc7a0114836fb5ba1edb14a86aa43b618"
    end
  end

  def install
    bin.install "gate-provider-review-gate"
    (share/"gate/providers").install "share/gate/providers/review-gate.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-review-gate"
  end
end
