# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateReview < Formula
  desc "Open a review ledger for the token parser change"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_tool_review_0.5.0_darwin_arm64.tar.gz"
  sha256 "97fd46440d693453f50a82ce17166618d49966ddf182a6da5f812e339bf56851"
  license "MIT"

  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_tool_review_0.5.0_darwin_arm64.tar.gz"
      sha256 "97fd46440d693453f50a82ce17166618d49966ddf182a6da5f812e339bf56851"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_tool_review_0.5.0_linux_arm64.tar.gz"
      sha256 "3357878ed81164bf6df0384ad863d793e8ad05f1bba9ef7f54c71a6de3f8ab5c"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_tool_review_0.5.0_linux_amd64.tar.gz"
      sha256 "7439e37a7b7c7397aa0a37dbe0bc185f8ffb6e1db3309411c699cb55b4814110"
    end
  end

  def install
    bin.install "review"
  end

  test do
    assert_match "review", shell_output("#{bin}/review --help 2>&1")
  end
end
