# This file is generated by hack/update.rb. Edit packages.yml instead.
class Gate < Formula
  desc "Apply local rules to agent tool calls"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_darwin_arm64.tar.gz"
  sha256 "721288c7e29cf65bce10d36725b146e53d42a8aa4635f276aa738cce72fec6e3"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_darwin_arm64.tar.gz"
      sha256 "721288c7e29cf65bce10d36725b146e53d42a8aa4635f276aa738cce72fec6e3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_linux_arm64.tar.gz"
      sha256 "eb6fbf3bb0ddbc2e0159c1a86ec06241242a6f0a8b8b27e156d581f8c92aa6f5"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_0.5.0_linux_amd64.tar.gz"
      sha256 "ec20f0461497c897f645c0228e4f14f2f8f260c57c73ac593c1b493b8c65278e"
    end
  end

  def install
    libexec.install "gate"
    (bin/"gate").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/gate" "$@"
    SH
    (bin/"gate").chmod 0755
  end

  test do
    assert_match "gate", shell_output("#{bin}/gate --help 2>&1")
  end
end
