# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderProseGate < Formula
  desc "Check a release note before publication"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_prose-gate_0.5.0_darwin_arm64.tar.gz"
  sha256 "dc7de50cf65b2c2c5f981de91abd31fd58fc2c7dd6798a14682b5ac684b3d150"
  license "MIT"

  depends_on "vale"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_prose-gate_0.5.0_darwin_arm64.tar.gz"
      sha256 "dc7de50cf65b2c2c5f981de91abd31fd58fc2c7dd6798a14682b5ac684b3d150"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_prose-gate_0.5.0_linux_arm64.tar.gz"
      sha256 "e9918b673b73d8d84f3481c8d52260660fe07101de092b3e24fbe8c8a6cdfd6b"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_prose-gate_0.5.0_linux_amd64.tar.gz"
      sha256 "b0c56d2ef41cb6359b86fbed0aa66be1a4ff292b5f2b558afc9e7b78ab2f4222"
    end
  end

  def install
    bin.install "gate-provider-prose-gate"
    (share/"gate/providers").install "share/gate/providers/prose-gate.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-prose-gate"
  end
end
