# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderNotes < Formula
  desc "Present an unanswered token validation note"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_notes_0.5.0_darwin_arm64.tar.gz"
  sha256 "2f56af60690c0f987617803de4a384f85802c592b6a9028afabc91811bd9b56b"
  license "MIT"

  depends_on "roshbhatia/tap/agent-notes"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_notes_0.5.0_darwin_arm64.tar.gz"
      sha256 "2f56af60690c0f987617803de4a384f85802c592b6a9028afabc91811bd9b56b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_notes_0.5.0_linux_arm64.tar.gz"
      sha256 "c95d2303b7bcc0e89e99011b0e8cae2ed8190d55fe1122c440f4289a165f2d91"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_notes_0.5.0_linux_amd64.tar.gz"
      sha256 "f726ed24f5b7dcf8f885c4b15d363d297b132659e93ff524c070b993d06516f1"
    end
  end

  def install
    bin.install "gate-provider-notes"
    (share/"gate/providers").install "share/gate/providers/notes.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-notes"
  end
end
