# This file is generated by hack/update.rb. Edit packages.yml instead.
class GateProviderNixGuard < Formula
  desc "Detect a managed configuration path before editing"
  homepage "https://github.com/roshbhatia/gate"
  url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_nix-guard_0.5.0_darwin_arm64.tar.gz"
  sha256 "7ec7a4dbf2f4144bb0246a6e941e591e92914a1b05b19b100d28a4e28a31cd19"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_nix-guard_0.5.0_darwin_arm64.tar.gz"
      sha256 "7ec7a4dbf2f4144bb0246a6e941e591e92914a1b05b19b100d28a4e28a31cd19"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_nix-guard_0.5.0_linux_arm64.tar.gz"
      sha256 "d212abc5ae8e5a9f33d7d7dc6558780499bf9b9a31acf0db33251f61490f0502"
    end
    on_intel do
      url "https://github.com/roshbhatia/gate/releases/download/v0.5.0/gate_provider_nix-guard_0.5.0_linux_amd64.tar.gz"
      sha256 "b726994d54bcc12e6db835f2770fdacd3486ae60d42a55e08599e73c1d3d50c0"
    end
  end

  def install
    bin.install "gate-provider-nix-guard"
    (share/"gate/providers").install "share/gate/providers/nix-guard.yaml"
  end

  test do
    assert_path_exists bin/"gate-provider-nix-guard"
  end
end
