# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderGithubAw < Formula
  desc "Track a real factory task through GitHub Actions"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_github-aw_0.12.8_darwin_arm64.tar.gz"
  sha256 "67a8023b1684f872474a7ffe95a59dcd837c923ce3c49250766ec85fd143a6a6"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "gh"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_github-aw_0.12.8_darwin_arm64.tar.gz"
      sha256 "67a8023b1684f872474a7ffe95a59dcd837c923ce3c49250766ec85fd143a6a6"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_github-aw_0.12.8_linux_arm64.tar.gz"
      sha256 "a8f1f84ad31dc4a837ddf6148abdce59fbafa6e4b416ea752e1381939250a311"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_github-aw_0.12.8_linux_amd64.tar.gz"
      sha256 "604cfb5a1cd3c4389bc79399a886f3246a462c11ff79cfdac772906f7769019b"
    end
  end

  def install
    libexec.install "orc-provider-github-aw"
    (share/"orc/providers").install "share/orc/providers/github-aw.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-github-aw").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-github-aw"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-github-aw" "$@"
    SH
    (bin/"orc-provider-github-aw").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-github-aw"
  end
end
