# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderChanges < Formula
  desc "Prepare a diff inspection for the token parser repair"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_changes_0.12.4_darwin_arm64.tar.gz"
  sha256 "29fbf673130ec2cd103c2c07010015a9d9b2b3a174f04660d7c8fbc5f08b133b"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "roshbhatia/tap/changes"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_changes_0.12.4_darwin_arm64.tar.gz"
      sha256 "29fbf673130ec2cd103c2c07010015a9d9b2b3a174f04660d7c8fbc5f08b133b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_changes_0.12.4_linux_arm64.tar.gz"
      sha256 "54365b61191a9ff56f80cae066a1fb128292cc0d39639f168827ab4663f40345"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_changes_0.12.4_linux_amd64.tar.gz"
      sha256 "f8c9e55aa911f56e9a6a091d4904a09e7eadfb436f1e34d7230fd8eebc95b231"
    end
  end

  def install
    libexec.install "orc-provider-changes"
    (share/"orc/providers").install "share/orc/providers/changes.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-changes").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-changes"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-changes" "$@"
    SH
    (bin/"orc-provider-changes").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-changes"
  end
end
