# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderLocal < Formula
  desc "Prepare the token parser test command"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_local_0.12.4_darwin_arm64.tar.gz"
  sha256 "431f7fdf3685cb2dcda658d5704051d534f57b90ea8c6420e3876ba16b2c9979"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_local_0.12.4_darwin_arm64.tar.gz"
      sha256 "431f7fdf3685cb2dcda658d5704051d534f57b90ea8c6420e3876ba16b2c9979"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_local_0.12.4_linux_arm64.tar.gz"
      sha256 "1b69df127484567f3fca449ff47d9010337c143c86df0da8238d591c3b534ccd"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_local_0.12.4_linux_amd64.tar.gz"
      sha256 "2b224b8931b3e68d0fd2ff02aea6fb16b586d5d23e193d9a9fd1f0405f8310a9"
    end
  end

  def install
    libexec.install "orc-provider-local"
    (share/"orc/providers").install "share/orc/providers/local.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-local").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-local"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-local" "$@"
    SH
    (bin/"orc-provider-local").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-local"
  end
end
