# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderTraces < Formula
  desc "Read the repair session activity"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_traces_0.12.3_darwin_arm64.tar.gz"
  sha256 "318b1194fb30db544bc7ca6a6aab6f1c5767b136fe086a690e7fb136dfa47cfd"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "roshbhatia/tap/traces"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_traces_0.12.3_darwin_arm64.tar.gz"
      sha256 "318b1194fb30db544bc7ca6a6aab6f1c5767b136fe086a690e7fb136dfa47cfd"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_traces_0.12.3_linux_arm64.tar.gz"
      sha256 "f4ee95bedaae856f40bd8ce420f5199058b28ebc03e86b39224f3cd721e3377e"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_traces_0.12.3_linux_amd64.tar.gz"
      sha256 "effeb4a797c3672f1854e7d8d1f12bcbede2cdef7c87c89b420850b22c065358"
    end
  end

  def install
    libexec.install "orc-provider-traces"
    (share/"orc/providers").install "share/orc/providers/traces.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-traces").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-traces"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-traces" "$@"
    SH
    (bin/"orc-provider-traces").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-traces"
  end
end
