# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderZmx < Formula
  include Language::Python::Virtualenv

  desc "Prepare a persistent repair session"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_zmx_0.12.5_darwin_arm64.tar.gz"
  sha256 "8010c94fc3444bfeabf037d9d93d238907fe5cae94eeb47bd7e1cdae98eb71c2"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "neurosnap/tap/zmx"
  depends_on "python@3.13"
  depends_on "uv"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_zmx_0.12.5_darwin_arm64.tar.gz"
      sha256 "8010c94fc3444bfeabf037d9d93d238907fe5cae94eeb47bd7e1cdae98eb71c2"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_zmx_0.12.5_linux_arm64.tar.gz"
      sha256 "d419de742abfa2d39fffe792d39ce5950377c069868b76d18ef7c85170c7ba45"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_zmx_0.12.5_linux_amd64.tar.gz"
      sha256 "2b521874ab572c12d22d64c1e21bd61593a852ddf20dbbbd741b3c621f3d72f1"
    end
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/8a/98/2d9906746cdc6a6ef809ae6338005b3f21bb568bea3165cfc6a243fdc25c/wheel-0.45.1.tar.gz"
    sha256 "661e1abd9198507b1409a20c02106d9670b2576e916d58f520316666abca6729"
  end
  resource "psutil" do
    url "https://files.pythonhosted.org/packages/2a/80/336820c1ad9286a4ded7e845b2eccfcb27851ab8ac6abece774a6ff4d3de/psutil-7.0.0.tar.gz"
    sha256 "7be9c3eba38beccb6495ea33afd982a44074b78f28c434a1f51cc07fd315c456"
  end

  def install
    libexec.install "orc-provider-zmx"
    (share/"orc/providers").install "share/orc/providers/zmx.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (libexec/"lib").install "lib/process_tree.py"
    venv = virtualenv_create(libexec/"venv", formula_opt_bin("python@3.13")/"python3.13")
    venv.pip_install resources
    site_packages = libexec/"venv/lib/python3.13/site-packages"
    (libexec/"wheels").mkpath
    wheel_source = buildpath/"wheels/psutil"
    wheel_source.mkpath
    wheel_files = [site_packages/"psutil", *Dir[site_packages/"psutil-*.dist-info"]]
    wheel_complete = wheel_files.length == 2 && wheel_files.all? { |file| File.exist?(file) }
    odie "Missing installed wheel metadata for psutil" unless wheel_complete
    cp_r wheel_files, wheel_source
    system libexec/"venv/bin/python", "-m", "wheel", "pack", wheel_source, "--dest-dir", libexec/"wheels"
    (libexec/"process-tree").write <<~SH
      #!/bin/sh
      exec "#{formula_opt_bin("uv")}/uv" run --offline --no-managed-python --no-python-downloads --no-project \\
        --python "#{formula_opt_bin("python@3.13")}/python3.13" --no-index --find-links "#{libexec}/wheels" \\
        --script "#{libexec}/lib/process_tree.py" "$@"
    SH
    (libexec/"process-tree").chmod 0755
    (bin/"orc-provider-zmx").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-zmx"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      export ORC_ZMX_TREE_HELPER="#{libexec}/process-tree"
      exec "#{libexec}/orc-provider-zmx" "$@"
    SH
    (bin/"orc-provider-zmx").chmod 0755
  end

  test do
    ENV["UV_CACHE_DIR"] = (testpath/"uv-cache").to_s
    assert_match "inspect", shell_output("#{libexec}/process-tree --help")
  end
end
