# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderHarness < Formula
  desc "Prepare the token parser review session"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_harness_0.12.3_darwin_arm64.tar.gz"
  sha256 "4bef3a1accf5371c87854826859efb456eb1d9aec3613706ff64524a6974261b"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_harness_0.12.3_darwin_arm64.tar.gz"
      sha256 "4bef3a1accf5371c87854826859efb456eb1d9aec3613706ff64524a6974261b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_harness_0.12.3_linux_arm64.tar.gz"
      sha256 "2f15c81f68094b8f81e774de9dcec419ede06313ac9e99d9365130318bb31dc5"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_harness_0.12.3_linux_amd64.tar.gz"
      sha256 "cb3adbc11bf8f9d8f79b7f9078a78cffd50d0a2456377c4d433a988af3e08a45"
    end
  end

  def install
    libexec.install "orc-provider-harness"
    (share/"orc/providers").install "share/orc/providers/harness.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-harness").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-harness"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-harness" "$@"
    SH
    (bin/"orc-provider-harness").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-harness"
  end
end
