# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderWezterm < Formula
  desc "Preview a terminal launch for the repair task"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_wezterm_0.12.8_darwin_arm64.tar.gz"
  sha256 "76d2304a7685f3db67563f2f5740091fe56feb2973e50e6ee19c27b722708f01"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_wezterm_0.12.8_darwin_arm64.tar.gz"
      sha256 "76d2304a7685f3db67563f2f5740091fe56feb2973e50e6ee19c27b722708f01"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_wezterm_0.12.8_linux_arm64.tar.gz"
      sha256 "47a4c1d5163543d36d75cdeab8e60bba8d00d62e156fe2e5e5998d1d0f15b017"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_wezterm_0.12.8_linux_amd64.tar.gz"
      sha256 "0b3d79b7369ee7c4d460d50068151dcaa5c78e8a4513357556f9d2241749f4df"
    end
  end

  def install
    libexec.install "orc-provider-wezterm"
    (share/"orc/providers").install "share/orc/providers/wezterm.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-wezterm").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-wezterm"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-wezterm" "$@"
    SH
    (bin/"orc-provider-wezterm").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-wezterm"
  end
end
