# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderHarness < Formula
  desc "Prepare the token parser review session"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_harness_0.12.8_darwin_arm64.tar.gz"
  sha256 "e1a1c4b61cf5824e6872bb753686da27ee78ccdae8a5a614f7d9d4cc43386c5c"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_harness_0.12.8_darwin_arm64.tar.gz"
      sha256 "e1a1c4b61cf5824e6872bb753686da27ee78ccdae8a5a614f7d9d4cc43386c5c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_harness_0.12.8_linux_arm64.tar.gz"
      sha256 "a3db2f2ded021fb1429b176c2015ffcf7f7b9d78e3a5ab0a5f91c1a2f1537764"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_harness_0.12.8_linux_amd64.tar.gz"
      sha256 "be3c4fb33388a81c799e5329a287473fda24c1b200a6162507eb355eef96d3dc"
    end
  end

  def install
    libexec.install "orc-provider-harness"
    (share/"orc/providers").install "share/orc/providers/harness.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-harness").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-harness"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-harness" "$@"
    SH
    (bin/"orc-provider-harness").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-harness"
  end
end
