# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcAll < Formula
  desc "All providers for orc"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_0.12.2_darwin_arm64.tar.gz"
  sha256 "96ced410e083dad4596609bdc4eb76a2ec7d56a26cd59169ddbc6ec6bf08527a"
  license "MIT"

  depends_on "roshbhatia/tap/orc"
  depends_on "roshbhatia/tap/orc-provider-changes"
  depends_on "roshbhatia/tap/orc-provider-harness"
  depends_on "roshbhatia/tap/orc-provider-local"
  depends_on "roshbhatia/tap/orc-provider-traces"
  depends_on "roshbhatia/tap/orc-provider-wezterm"
  depends_on "roshbhatia/tap/orc-provider-zmx"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_0.12.2_darwin_arm64.tar.gz"
      sha256 "96ced410e083dad4596609bdc4eb76a2ec7d56a26cd59169ddbc6ec6bf08527a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_0.12.2_linux_arm64.tar.gz"
      sha256 "0b73433883450572dbea3331459dd5a225d0b6ccbdc641e5294f82a34c5fc4c2"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_0.12.2_linux_amd64.tar.gz"
      sha256 "2c541003a366a4677d37a3f678da9daf9e5007d9f1bde8f793fbcb65fe44ba0b"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      orc
      orc-provider-changes
      orc-provider-harness
      orc-provider-local
      orc-provider-traces
      orc-provider-wezterm
      orc-provider-zmx
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
