# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderLocal < Formula
  desc "Prepare the token parser test command"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_local_0.12.3_darwin_arm64.tar.gz"
  sha256 "ec84958bb07e772ee22b1b3741022f0a801e44f75b6ff6fb24f55c52d460b4d3"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_local_0.12.3_darwin_arm64.tar.gz"
      sha256 "ec84958bb07e772ee22b1b3741022f0a801e44f75b6ff6fb24f55c52d460b4d3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_local_0.12.3_linux_arm64.tar.gz"
      sha256 "e39138bee44d1b649f5cf43158ee17a29597003ed9719c721128d8c03d0b29c0"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.3/orc_provider_local_0.12.3_linux_amd64.tar.gz"
      sha256 "03cd08c0d356a49d88d396cae4f96cd9872b5f419ab225d57051cf9ae8c6ef5b"
    end
  end

  def install
    libexec.install "orc-provider-local"
    (share/"orc/providers").install "share/orc/providers/local.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-local").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-local"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-local" "$@"
    SH
    (bin/"orc-provider-local").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-local"
  end
end
