# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderChanges < Formula
  desc "Prepare a diff inspection for the token parser repair"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_changes_0.12.5_darwin_arm64.tar.gz"
  sha256 "3f8abbd0eb77024a9896609c2d6edfab7a6f9a4c801741caac9a70e4bef49bcc"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "roshbhatia/tap/changes"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_changes_0.12.5_darwin_arm64.tar.gz"
      sha256 "3f8abbd0eb77024a9896609c2d6edfab7a6f9a4c801741caac9a70e4bef49bcc"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_changes_0.12.5_linux_arm64.tar.gz"
      sha256 "ab7003beda97edc2222f71fecdd3a5e4e088684295f16bc8034fc2848540ab3c"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_changes_0.12.5_linux_amd64.tar.gz"
      sha256 "e4eb974d4af038f9f10fa5644de1b735febe3c9158625a3563ec3c1d1070df24"
    end
  end

  def install
    libexec.install "orc-provider-changes"
    (share/"orc/providers").install "share/orc/providers/changes.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-changes").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-changes"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-changes" "$@"
    SH
    (bin/"orc-provider-changes").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-changes"
  end
end
