# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderWezterm < Formula
  desc "Preview a terminal launch for the repair task"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_wezterm_0.12.2_darwin_arm64.tar.gz"
  sha256 "06d275f29a1a90b4c4cadd907824a12ec1956c2f4603a48656a1c2e18be08726"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_wezterm_0.12.2_darwin_arm64.tar.gz"
      sha256 "06d275f29a1a90b4c4cadd907824a12ec1956c2f4603a48656a1c2e18be08726"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_wezterm_0.12.2_linux_arm64.tar.gz"
      sha256 "cbf2c9ff9c3f97c2ffef2ebfa433f490bacf82eb1db13fc51cc0525c20812cd0"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_wezterm_0.12.2_linux_amd64.tar.gz"
      sha256 "4455f84df782adcfcd2b0ec9a125044b0b559a06a1a1b52a13fe041c4c389b8b"
    end
  end

  def install
    libexec.install "orc-provider-wezterm"
    (share/"orc/providers").install "share/orc/providers/wezterm.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-wezterm").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-wezterm"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-wezterm" "$@"
    SH
    (bin/"orc-provider-wezterm").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-wezterm"
  end
end
