# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcAll < Formula
  desc "All providers for orc"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_0.12.8_darwin_arm64.tar.gz"
  sha256 "5f27551bfb130a848ef5692e9525492bc9d2ee4c0ef93e5b72b9ba2bb36fc605"
  license "MIT"

  depends_on "roshbhatia/tap/orc"
  depends_on "roshbhatia/tap/orc-provider-changes"
  depends_on "roshbhatia/tap/orc-provider-github-aw"
  depends_on "roshbhatia/tap/orc-provider-harness"
  depends_on "roshbhatia/tap/orc-provider-local"
  depends_on "roshbhatia/tap/orc-provider-traces"
  depends_on "roshbhatia/tap/orc-provider-wezterm"
  depends_on "roshbhatia/tap/orc-provider-zmx"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_0.12.8_darwin_arm64.tar.gz"
      sha256 "5f27551bfb130a848ef5692e9525492bc9d2ee4c0ef93e5b72b9ba2bb36fc605"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_0.12.8_linux_arm64.tar.gz"
      sha256 "a4b18e35aa436f47a59e79932e6a6acb555996864640cb82c38db12518ba0e1e"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_0.12.8_linux_amd64.tar.gz"
      sha256 "908c0606ed233f052d3b76b20ef06db13fa359173511bb2086052526093a6bb5"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      orc
      orc-provider-changes
      orc-provider-github-aw
      orc-provider-harness
      orc-provider-local
      orc-provider-traces
      orc-provider-wezterm
      orc-provider-zmx
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
