# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderGithubAw < Formula
  desc "Track a real factory task through GitHub Actions"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_github-aw_0.12.4_darwin_arm64.tar.gz"
  sha256 "c4b74daab259f01e94c99031d86255658d7445cf1c099981b7e894ba3380faae"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "gh"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_github-aw_0.12.4_darwin_arm64.tar.gz"
      sha256 "c4b74daab259f01e94c99031d86255658d7445cf1c099981b7e894ba3380faae"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_github-aw_0.12.4_linux_arm64.tar.gz"
      sha256 "918716f77b57e663aa5c4429e8347dad54b7a510aedeb1bcadab40edec5801b9"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_github-aw_0.12.4_linux_amd64.tar.gz"
      sha256 "4e99fe3be83ef6bde99475acf06951dcc3433c2cf14e2317e40bf9ff168c36f9"
    end
  end

  def install
    libexec.install "orc-provider-github-aw"
    (share/"orc/providers").install "share/orc/providers/github-aw.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-github-aw").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-github-aw"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-github-aw" "$@"
    SH
    (bin/"orc-provider-github-aw").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-github-aw"
  end
end
