# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderLocal < Formula
  desc "Prepare the token parser test command"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_local_0.12.8_darwin_arm64.tar.gz"
  sha256 "8526dd208e7d627a263fe3a41731bcf69aee40b9644b3a9456b1c736bc5fd488"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_local_0.12.8_darwin_arm64.tar.gz"
      sha256 "8526dd208e7d627a263fe3a41731bcf69aee40b9644b3a9456b1c736bc5fd488"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_local_0.12.8_linux_arm64.tar.gz"
      sha256 "fb1b9dbfc1c574e0733b84d235649b123b44383a6c7a3b9aed358d1d3eb8d60b"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.8/orc_provider_local_0.12.8_linux_amd64.tar.gz"
      sha256 "f692013ce4605a6605497ec3ef47271417a8f1720c989f9197c564b63c1854bb"
    end
  end

  def install
    libexec.install "orc-provider-local"
    (share/"orc/providers").install "share/orc/providers/local.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-local").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-local"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-local" "$@"
    SH
    (bin/"orc-provider-local").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-local"
  end
end
