# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderZmx < Formula
  include Language::Python::Virtualenv

  desc "Prepare a persistent repair session"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_zmx_0.12.2_darwin_arm64.tar.gz"
  sha256 "1ba99f5ac7233e65b94ab853933ada36e68f3c3c36d61b547e9b8ba1ce383c41"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "neurosnap/tap/zmx"
  depends_on "python@3.13"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_zmx_0.12.2_darwin_arm64.tar.gz"
      sha256 "1ba99f5ac7233e65b94ab853933ada36e68f3c3c36d61b547e9b8ba1ce383c41"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_zmx_0.12.2_linux_arm64.tar.gz"
      sha256 "4cb2b1de39ca20629211df2cf07f3569ebf8c4ce77ed0ba22634ca96ee0e9712"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_zmx_0.12.2_linux_amd64.tar.gz"
      sha256 "c6653c109b3d408b5731f9cfa75ef19801cf15d9462aded5909f1d161d7d92ee"
    end
  end

  resource "psutil" do
    url "https://files.pythonhosted.org/packages/2a/80/336820c1ad9286a4ded7e845b2eccfcb27851ab8ac6abece774a6ff4d3de/psutil-7.0.0.tar.gz"
    sha256 "7be9c3eba38beccb6495ea33afd982a44074b78f28c434a1f51cc07fd315c456"
  end

  def install
    libexec.install "orc-provider-zmx"
    (share/"orc/providers").install "share/orc/providers/zmx.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (libexec/"lib").install "lib/process_tree.py"
    venv = virtualenv_create(libexec/"venv", formula_opt_bin("python@3.13")/"python3.13")
    venv.pip_install resources
    (libexec/"process-tree").write <<~SH
      #!/bin/sh
      exec "#{libexec}/venv/bin/python" "#{libexec}/lib/process_tree.py" "$@"
    SH
    (libexec/"process-tree").chmod 0755
    (bin/"orc-provider-zmx").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-zmx"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      export ORC_ZMX_TREE_HELPER="#{libexec}/process-tree"
      exec "#{libexec}/orc-provider-zmx" "$@"
    SH
    (bin/"orc-provider-zmx").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-zmx"
  end
end
