# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderWezterm < Formula
  desc "Preview a terminal launch for the repair task"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_wezterm_0.12.4_darwin_arm64.tar.gz"
  sha256 "16493ceda5e75123d37752389cb918fc8ab7803002560fa2451dbfdb2e431608"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_wezterm_0.12.4_darwin_arm64.tar.gz"
      sha256 "16493ceda5e75123d37752389cb918fc8ab7803002560fa2451dbfdb2e431608"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_wezterm_0.12.4_linux_arm64.tar.gz"
      sha256 "c07852f551a71ed7f7bf2e95181dc47d8bd8192497f6135f87698206e733996e"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_wezterm_0.12.4_linux_amd64.tar.gz"
      sha256 "41c56e11f0147dcb55b107c9d0b864bded017545f420d72f8bb28bd8004bbc10"
    end
  end

  def install
    libexec.install "orc-provider-wezterm"
    (share/"orc/providers").install "share/orc/providers/wezterm.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-wezterm").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-wezterm"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-wezterm" "$@"
    SH
    (bin/"orc-provider-wezterm").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-wezterm"
  end
end
