# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderTraces < Formula
  desc "Read the repair session activity"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_traces_0.12.2_darwin_arm64.tar.gz"
  sha256 "39eeba68aecd14aada9365ad945bcdd4d90caeaa59ab5b7fae409cca1cd57b78"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "roshbhatia/tap/traces"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_traces_0.12.2_darwin_arm64.tar.gz"
      sha256 "39eeba68aecd14aada9365ad945bcdd4d90caeaa59ab5b7fae409cca1cd57b78"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_traces_0.12.2_linux_arm64.tar.gz"
      sha256 "a43093bd17210dd37f9fe2f4a70e10d2526cee5f8619d080fc7ad9b065f7a6d0"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_traces_0.12.2_linux_amd64.tar.gz"
      sha256 "6044e0b6bf875269e3709c3134d7713e759372344e9a88dc17ba952208168df6"
    end
  end

  def install
    libexec.install "orc-provider-traces"
    (share/"orc/providers").install "share/orc/providers/traces.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-traces").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{Formula["bash"].opt_bin}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-traces"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-traces" "$@"
    SH
    (bin/"orc-provider-traces").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-traces"
  end
end
