# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderHarness < Formula
  desc "Prepare the token parser review session"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_harness_0.12.4_darwin_arm64.tar.gz"
  sha256 "b342e9b77beb40a9ad8e748cf236d4a38f6c0cc0ad624c0df320b661c8832aac"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_harness_0.12.4_darwin_arm64.tar.gz"
      sha256 "b342e9b77beb40a9ad8e748cf236d4a38f6c0cc0ad624c0df320b661c8832aac"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_harness_0.12.4_linux_arm64.tar.gz"
      sha256 "5e623abf4e2568068d53d1439cbda33a70093c56427616c0ae62764c2b020c59"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_harness_0.12.4_linux_amd64.tar.gz"
      sha256 "d3c706decf39d01095c56bbd82a96d774a5635c16c737e6bd967f9abac324211"
    end
  end

  def install
    libexec.install "orc-provider-harness"
    (share/"orc/providers").install "share/orc/providers/harness.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-harness").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-harness"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-harness" "$@"
    SH
    (bin/"orc-provider-harness").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-harness"
  end
end
