# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderChanges < Formula
  desc "Prepare a diff inspection for the token parser repair"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_changes_0.12.2_darwin_arm64.tar.gz"
  sha256 "74970548723fffe10292f16edeb2e22dda19d9a13149298f61dc4908be06e777"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "roshbhatia/tap/changes"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_changes_0.12.2_darwin_arm64.tar.gz"
      sha256 "74970548723fffe10292f16edeb2e22dda19d9a13149298f61dc4908be06e777"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_changes_0.12.2_linux_arm64.tar.gz"
      sha256 "e7a1c3530c33fee761d7bd1fff32319cc7a16508163b9c81eacc95e26ac86fab"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.2/orc_provider_changes_0.12.2_linux_amd64.tar.gz"
      sha256 "c1e3cb03408c4d92a7a8eb412808c09e12f7e971a150d71bd3a9d5c3cb50f22d"
    end
  end

  def install
    libexec.install "orc-provider-changes"
    (share/"orc/providers").install "share/orc/providers/changes.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-changes").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{Formula["bash"].opt_bin}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-changes"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-changes" "$@"
    SH
    (bin/"orc-provider-changes").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-changes"
  end
end
