# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderGithubAw < Formula
  desc "Track a real factory task through GitHub Actions"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_github-aw_0.12.5_darwin_arm64.tar.gz"
  sha256 "c8a9822ca9e0740b9e46e3e55833aa801dd1c3b08967e43a940505a3d2cbda57"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "gh"
  depends_on "jq"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_github-aw_0.12.5_darwin_arm64.tar.gz"
      sha256 "c8a9822ca9e0740b9e46e3e55833aa801dd1c3b08967e43a940505a3d2cbda57"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_github-aw_0.12.5_linux_arm64.tar.gz"
      sha256 "6609add202577335bf4666c17b6338c1e4361d6f626ae2f59c7fbdf65acf434b"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_provider_github-aw_0.12.5_linux_amd64.tar.gz"
      sha256 "a423051766d1d053bbf35a24e6d5576be1528699a15a62ba8d98e812fdd15043"
    end
  end

  def install
    libexec.install "orc-provider-github-aw"
    (share/"orc/providers").install "share/orc/providers/github-aw.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-github-aw").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-github-aw"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-github-aw" "$@"
    SH
    (bin/"orc-provider-github-aw").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-github-aw"
  end
end
