# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcAll < Formula
  desc "All providers for orc"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_0.12.5_darwin_arm64.tar.gz"
  sha256 "aab5360806b7e03aa6c5a847032be917971fce33a00384bb0c8fe727c323b324"
  license "MIT"

  depends_on "roshbhatia/tap/orc"
  depends_on "roshbhatia/tap/orc-provider-changes"
  depends_on "roshbhatia/tap/orc-provider-github-aw"
  depends_on "roshbhatia/tap/orc-provider-harness"
  depends_on "roshbhatia/tap/orc-provider-local"
  depends_on "roshbhatia/tap/orc-provider-traces"
  depends_on "roshbhatia/tap/orc-provider-wezterm"
  depends_on "roshbhatia/tap/orc-provider-zmx"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_0.12.5_darwin_arm64.tar.gz"
      sha256 "aab5360806b7e03aa6c5a847032be917971fce33a00384bb0c8fe727c323b324"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_0.12.5_linux_arm64.tar.gz"
      sha256 "d8607b78592aeb1b8d1a76bc6fe4cbd6bfb4213104f8da6b93f07806fe2ce382"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.5/orc_0.12.5_linux_amd64.tar.gz"
      sha256 "dffb7a3c337810ac3cd27fc66af34ed3b69e39e853008aa49085100404c17733"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      orc
      orc-provider-changes
      orc-provider-github-aw
      orc-provider-harness
      orc-provider-local
      orc-provider-traces
      orc-provider-wezterm
      orc-provider-zmx
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
