# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class OrcProviderTraces < Formula
  desc "Read the repair session activity"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_traces_0.12.4_darwin_arm64.tar.gz"
  sha256 "a70aed80e11423e9dbe9259463469ce050ab5386e7028bed7e747a1d7a08fb93"
  license "MIT"

  depends_on "bash"
  depends_on "coreutils"
  depends_on "jq"
  depends_on "roshbhatia/tap/traces"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_traces_0.12.4_darwin_arm64.tar.gz"
      sha256 "a70aed80e11423e9dbe9259463469ce050ab5386e7028bed7e747a1d7a08fb93"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_traces_0.12.4_linux_arm64.tar.gz"
      sha256 "821cd35dc58ed52c8a0d55cec420ee98467391c10654b130530e24b58a86279f"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_provider_traces_0.12.4_linux_amd64.tar.gz"
      sha256 "f0f60592d7fbe7e0b3cbea5a8a954a0b36bb4139e1127ae9d67fa3e0d5b1c633"
    end
  end

  def install
    libexec.install "orc-provider-traces"
    (share/"orc/providers").install "share/orc/providers/traces.yaml"
    (libexec/"lib").install "lib/provider.sh"
    (bin/"orc-provider-traces").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      export PATH="#{formula_opt_bin("bash")}:$PATH"
      export ORC_PROVIDER_SELF="#{bin}/orc-provider-traces"
      export ORC_PROVIDER_LIB="#{libexec}/lib/provider.sh"
      exec "#{libexec}/orc-provider-traces" "$@"
    SH
    (bin/"orc-provider-traces").chmod 0755
  end

  test do
    assert_path_exists bin/"orc-provider-traces"
  end
end
