# This file is generated by hack/update.rb. Edit packages.yml instead.
class Orc < Formula
  desc "Provider-neutral control plane for agent workflows"
  homepage "https://github.com/roshbhatia/orc"
  version "0.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.10.0/orc_0.10.0_darwin_arm64.tar.gz"
      sha256 "4af14a1545f165525a535f9d9e7db5fe0b782f6177ed9db01458449679477f5c"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.10.0/orc_0.10.0_darwin_amd64.tar.gz"
      sha256 "4f367dae5d68b795a55c761f85e09d73c0f7b0109e7c32fea8df0c244375649b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.10.0/orc_0.10.0_linux_arm64.tar.gz"
      sha256 "b0ea47dc5962c63462d67b7e9ca62ef19c7e139dfb2a4a300a8a833d3fe81739"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.10.0/orc_0.10.0_linux_amd64.tar.gz"
      sha256 "e6fe6493df94b3381001df010d62e81e2fb50c557a13037b1109c8cbe0aff34e"
    end
  end

  def install
    archive_root = Dir["orc_0.10.0_*_*"].find { |path| File.directory?(path) }
    odie "release archive has no orc root" unless archive_root

    bin.install "#{archive_root}/bin/orc"
    bash_completion.install "#{archive_root}/share/bash-completion/completions/orc"
    zsh_completion.install "#{archive_root}/share/zsh/site-functions/_orc"
    fish_completion.install "#{archive_root}/share/fish/vendor_completions.d/orc.fish"
    (share/"nushell/vendor/autoload").install "#{archive_root}/share/nushell/vendor/autoload/orc.nu"
    (share/"orc").install Dir["#{archive_root}/share/orc/*"]
  end

  test do
    assert_match "orc", shell_output("#{bin}/orc --help")
  end
end
