# This file is generated by hack/update.rb. Edit packages.yml instead.
class Orc < Formula
  desc "Provider-neutral control plane for agent workflows"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.1/orc_0.12.1_darwin_arm64.tar.gz"
  sha256 "67b7fed431c3afa6cd4575f42856423baef601162eedacfd23710419f40bcf4c"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.1/orc_0.12.1_darwin_arm64.tar.gz"
      sha256 "67b7fed431c3afa6cd4575f42856423baef601162eedacfd23710419f40bcf4c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.1/orc_0.12.1_linux_arm64.tar.gz"
      sha256 "7f8d0c7b50eb61b5e37f3da213a42c8390a22825d4e76023cf2a257ed565688e"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.1/orc_0.12.1_linux_amd64.tar.gz"
      sha256 "590ed67d4e9a7d93d0ed76879bc69b6d4db8901508d9117e05a9489a409acc57"
    end
  end

  def install
    archive_root = Dir["orc_0.12.1_*_*"]
                   .find { |path| File.directory?(path) } || buildpath

    libexec.install "#{archive_root}/bin/orc"
    bash_completion.install "#{archive_root}/share/bash-completion/completions/orc"
    zsh_completion.install "#{archive_root}/share/zsh/site-functions/_orc"
    fish_completion.install "#{archive_root}/share/fish/vendor_completions.d/orc.fish"
    (share/"nushell/vendor/autoload").install "#{archive_root}/share/nushell/vendor/autoload/orc.nu"
    pkgshare.install Dir["#{archive_root}/share/orc/*"]
    (bin/"orc").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/orc" "$@"
    SH
    (bin/"orc").chmod 0755
  end

  test do
    assert_match "orc", shell_output("#{bin}/orc --help 2>&1")
  end
end
