# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class Orc < Formula
  desc "Provider-neutral control plane for agent workflows"
  homepage "https://github.com/roshbhatia/orc"
  url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_0.12.4_darwin_arm64.tar.gz"
  sha256 "00974a7e63ec562525af45968419f2349fd88451724e6191f88f2d9002ecf68b"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_0.12.4_darwin_arm64.tar.gz"
      sha256 "00974a7e63ec562525af45968419f2349fd88451724e6191f88f2d9002ecf68b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_0.12.4_linux_arm64.tar.gz"
      sha256 "13b5b2e920bebc1fe79b9b4d3d604f8add36cc9d3ea23a263ec0f85940c985aa"
    end
    on_intel do
      url "https://github.com/roshbhatia/orc/releases/download/v0.12.4/orc_0.12.4_linux_amd64.tar.gz"
      sha256 "587b7db14e972b8d3b045f5d623cb189f3e90de03846b03eb877c557e5954d5e"
    end
  end

  def install
    archive_root = Dir["orc_0.12.4_*_*"]
                   .find { |path| File.directory?(path) } || buildpath

    libexec.install "#{archive_root}/bin/orc"
    bash_completion.install "#{archive_root}/share/bash-completion/completions/orc"
    zsh_completion.install "#{archive_root}/share/zsh/site-functions/_orc"
    fish_completion.install "#{archive_root}/share/fish/vendor_completions.d/orc.fish"
    (share/"nushell/vendor/autoload").install "#{archive_root}/share/nushell/vendor/autoload/orc.nu"
    pkgshare.install Dir["#{archive_root}/share/orc/*"]
    (bin/"orc").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/orc" "$@"
    SH
    (bin/"orc").chmod 0755
  end

  test do
    assert_match "orc", shell_output("#{bin}/orc --help 2>&1")
  end
end
