# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class SeshyProviderWezterm < Formula
  desc "Open Seshy sessions from the WezTerm picker"
  homepage "https://github.com/roshbhatia/seshy"
  license "MIT"

  depends_on "roshbhatia/tap/seshy"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_provider_wezterm_5.0.1_darwin_arm64.tar.gz"
      sha256 "1e9f7ad8160e576acd41a69a27576ff837248df6c136fafc3837f62c27d93f23"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_provider_wezterm_5.0.1_darwin_amd64.tar.gz"
      sha256 "017abef82f0f2479cb846bff64aea999daea6bb52251288e6c3ca43efc1c21ff"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_provider_wezterm_5.0.1_linux_arm64.tar.gz"
      sha256 "50fa7806e58569bdbc80d7797100fceae03a3fecf727d570ebda6fb2f3f5418b"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_provider_wezterm_5.0.1_linux_amd64.tar.gz"
      sha256 "163412be21fd3a6300fbd89a9f6ea354812db1ae3a5aa6f1a8e65ecc435e1a43"
    end
  end

  def install
    bin.install "seshy-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/seshy.json"
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/seshy-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
