# This file is generated by hack/update.rb. Edit packages.yml instead.
class Seshy < Formula
  desc "Multi-repository worktree session manager"
  homepage "https://github.com/roshbhatia/seshy"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v4.1.0/seshy_4.1.0_darwin_arm64.tar.gz"
      sha256 "5053b6ffc0b2fdcd33b90033bf7f58839eb747cece337649ba28b224891335d0"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v4.1.0/seshy_4.1.0_darwin_amd64.tar.gz"
      sha256 "86cf02af01b3f2209331f1910dbb8283a2187df9cd91219c6fc6b1dd3142ed7a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v4.1.0/seshy_4.1.0_linux_arm64.tar.gz"
      sha256 "f439ba27b6f82f81122794b973f7f798adfb8513765ef0b8bc074ab93ae4d658"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v4.1.0/seshy_4.1.0_linux_amd64.tar.gz"
      sha256 "d1f011fe60a17e197755ed017927eb02275e471922190af0c57d9443dc62ecaa"
    end
  end

  def install
    bin.install "sy"
    generate_completions_from_executable(bin/"sy", "completion")
    nu_completion = buildpath/"sy.nu"
    nu_completion.write Utils.safe_popen_read(bin/"sy", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "sy", shell_output("#{bin}/sy --help")
  end
end
