# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class SeshyProviderWezterm < Formula
  desc "Select a checkout group for token parser review"
  homepage "https://github.com/roshbhatia/seshy"
  license "MIT"

  depends_on "python@3.13"
  depends_on "roshbhatia/tap/seshy"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_provider_wezterm_5.0.0_darwin_arm64.tar.gz"
      sha256 "093675fc375700f327d5147ab8eaaab8e55c373175d41549b747fc109c2243e1"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_provider_wezterm_5.0.0_darwin_amd64.tar.gz"
      sha256 "5c603237edde3b25f78c79292813b9b6c28560675101d9e07ae7d4e3f25fd256"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_provider_wezterm_5.0.0_linux_arm64.tar.gz"
      sha256 "54016837ccfc715fcbd77bcda4eff5c687bc5ca0ded3a51b60b85587dc0d52c1"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_provider_wezterm_5.0.0_linux_amd64.tar.gz"
      sha256 "4a9161d208789e50d5d47f0b89f0e7b49c3f4fa9d5dca7ed0577ed013b343657"
    end
  end

  def install
    libexec.install "seshy-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/seshy.json"
    (bin/"seshy-picker").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{formula_opt_bin("python@3.13")}/python3.13" "#{libexec}/seshy-picker" "$@"
    SH
    (bin/"seshy-picker").chmod 0755
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/seshy-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
