# This file is generated by hack/update.rb. Edit packages.yml instead.
class SeshyAll < Formula
  desc "seshy with all provider packages"
  homepage "https://github.com/roshbhatia/seshy"
  license "MIT"

  depends_on "roshbhatia/tap/seshy"
  depends_on "roshbhatia/tap/seshy-provider-wezterm"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_darwin_arm64.tar.gz"
      sha256 "70d8e1db3aa33e4b24dba632f5c2ed98c189bbe7d1f2ec31deb03a9e2b72fd57"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_darwin_amd64.tar.gz"
      sha256 "0c95818b7f802d05b572d9e206c69807aaeb81fc9f256f41a2a90e4bd961e011"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_linux_arm64.tar.gz"
      sha256 "cb0bbbefa90ea71c63469063efc6c8da9876e82a2442a527c526a455016179b4"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_linux_amd64.tar.gz"
      sha256 "a0cd036a39d79df1fda3b9eed5c2f38fe11f4f7a58145f3e90860657ced39549"
    end
  end

  def install
    (pkgshare/"providers.txt").write "seshy\nseshy-provider-wezterm\n"
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
