# This file is generated by hack/update.rb. Edit packages.yml instead.
class Seshy < Formula
  desc "Multi-repository worktree session manager"
  homepage "https://github.com/roshbhatia/seshy"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_darwin_arm64.tar.gz"
      sha256 "70d8e1db3aa33e4b24dba632f5c2ed98c189bbe7d1f2ec31deb03a9e2b72fd57"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_darwin_amd64.tar.gz"
      sha256 "0c95818b7f802d05b572d9e206c69807aaeb81fc9f256f41a2a90e4bd961e011"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_linux_arm64.tar.gz"
      sha256 "cb0bbbefa90ea71c63469063efc6c8da9876e82a2442a527c526a455016179b4"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.0/seshy_5.0.0_linux_amd64.tar.gz"
      sha256 "a0cd036a39d79df1fda3b9eed5c2f38fe11f4f7a58145f3e90860657ced39549"
    end
  end

  def install
    bin.install "sy"
    generate_completions_from_executable(bin/"sy", "completion")
    nu_completion = buildpath/"sy.nu"
    nu_completion.write Utils.safe_popen_read(bin/"sy", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "sy", shell_output("#{bin}/sy --help 2>&1")
  end
end
