# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class SeshyAll < Formula
  desc "All providers for seshy"
  homepage "https://github.com/roshbhatia/seshy"
  license "MIT"

  depends_on "roshbhatia/tap/seshy"
  depends_on "roshbhatia/tap/seshy-provider-wezterm"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_5.0.1_darwin_arm64.tar.gz"
      sha256 "600a359b58f9f428afb93538c583e1b0d55d194d0ddbe7a433e53788bbab5b3e"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_5.0.1_darwin_amd64.tar.gz"
      sha256 "9612eea26c9265960d304333ab8138130855902f3c6ea69630ce054024d7c27c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_5.0.1_linux_arm64.tar.gz"
      sha256 "455da05ab6058682d829ac06e2c9d2b331fc349d1069ecebf21d7d6d43791d4b"
    end
    on_intel do
      url "https://github.com/roshbhatia/seshy/releases/download/v5.0.1/seshy_5.0.1_linux_amd64.tar.gz"
      sha256 "4266368d98f3ef9a82f9a8510f778f6863281972d9da1aef85270e30412b2530"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      seshy
      seshy-provider-wezterm
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
