# This file is generated by hack/update.rb. Edit packages.yml instead.
class Specutil < Formula
  desc "Project OpenSpec changes into review-ready outputs"
  homepage "https://github.com/roshbhatia/specutil"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.2.0/specutil_0.2.0_darwin_arm64.tar.gz"
      sha256 "c298eb844e5f1c8053ed0ed76c4a43b0b802672dbbb270e9630a9786f0d5f142"
    end
    on_intel do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.2.0/specutil_0.2.0_darwin_amd64.tar.gz"
      sha256 "83505a40ca5bb430ef42fd30bd12d6c9b7916ea27a54fa7d49eecadc5c8a89ee"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.2.0/specutil_0.2.0_linux_arm64.tar.gz"
      sha256 "2b14d3abcd987e830721421e8914094956e3d832b3d282e7bd0551f33743c943"
    end
    on_intel do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.2.0/specutil_0.2.0_linux_amd64.tar.gz"
      sha256 "71013def6b1da884b459c1150dd7074940e7929a7c3616362c7c8a4f1a4b31f4"
    end
  end

  def install
    bin.install "specutil"
    generate_completions_from_executable(bin/"specutil", "completion")
    nu_completion = buildpath/"specutil.nu"
    nu_completion.write Utils.safe_popen_read(bin/"specutil", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "specutil", shell_output("#{bin}/specutil --help")
  end
end
