# This file is generated by hack/update.rb. Edit packages.yml instead.
class Specutil < Formula
  desc "Project OpenSpec changes into review-ready outputs"
  homepage "https://github.com/roshbhatia/specutil"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.3.0/specutil_0.3.0_darwin_arm64.tar.gz"
      sha256 "6343ce74689a368ddb7036aee286e31a7b0de06ff2dcc4b3d5d30292ac7f639f"
    end
    on_intel do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.3.0/specutil_0.3.0_darwin_amd64.tar.gz"
      sha256 "ee139775607ffccbc65e7317b96b1efd998f11d5f6a5d3cb6b87b6801d006de2"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.3.0/specutil_0.3.0_linux_arm64.tar.gz"
      sha256 "693ddc010e34bb63924e985e46235503e52b8efc47b7df24d565af050fa5cfe7"
    end
    on_intel do
      url "https://github.com/roshbhatia/specutil/releases/download/v0.3.0/specutil_0.3.0_linux_amd64.tar.gz"
      sha256 "f2e7256b207029e5eaa134b795b9c202ababd4b1e87e6297bb2f833333c8868f"
    end
  end

  def install
    bin.install "specutil"
    generate_completions_from_executable(bin/"specutil", "completion")
    nu_completion = buildpath/"specutil.nu"
    nu_completion.write Utils.safe_popen_read(bin/"specutil", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "specutil", shell_output("#{bin}/specutil --help")
  end
end
