# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class SysinitWeztermProviderZoxide < Formula
  desc "Open zoxide directories from the WezTerm picker"
  homepage "https://github.com/roshbhatia/sysinit.wezterm"
  url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zoxide_0.1.2_darwin_arm64.tar.gz"
  sha256 "4b054b17013f9895645639fa1ff3d367b45fdf10cd79b7efa322bd886331e7a0"
  license "MIT"
  revision 1

  depends_on "python@3.13"
  depends_on "uv"
  depends_on "zoxide"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zoxide_0.1.2_darwin_arm64.tar.gz"
      sha256 "4b054b17013f9895645639fa1ff3d367b45fdf10cd79b7efa322bd886331e7a0"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zoxide_0.1.2_linux_arm64.tar.gz"
      sha256 "ac5c8619a1dd57a425d8c9223ba0c3d5094d39d6b1947f9baa08a1512cc693ab"
    end
    on_intel do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zoxide_0.1.2_linux_amd64.tar.gz"
      sha256 "ad6b51cf698974442f550612398f9e212d75606f4584df5ff0297483ac71820c"
    end
  end

  def install
    libexec.install "zoxide-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/zoxide.json"
    (bin/"zoxide-picker").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{formula_opt_bin("uv")}/uv" --no-cache run --offline --no-managed-python --no-python-downloads --no-project \\
        --python "#{formula_opt_bin("python@3.13")}/python3.13" --script "#{libexec}/zoxide-picker" "$@"
    SH
    (bin/"zoxide-picker").chmod 0755
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/zoxide-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
