# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class SysinitWeztermProviderZmx < Formula
  desc "Attach persistent Zmx sessions from the WezTerm picker"
  homepage "https://github.com/roshbhatia/sysinit.wezterm"
  url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zmx_0.1.2_darwin_arm64.tar.gz"
  sha256 "00ad3c9bc5c17fea88b1339659f3ad2f5f2954c2ee8ebdb0e3a2f4a819ab0958"
  license "MIT"
  revision 1

  depends_on "neurosnap/tap/zmx"
  depends_on "python@3.13"
  depends_on "uv"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zmx_0.1.2_darwin_arm64.tar.gz"
      sha256 "00ad3c9bc5c17fea88b1339659f3ad2f5f2954c2ee8ebdb0e3a2f4a819ab0958"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zmx_0.1.2_linux_arm64.tar.gz"
      sha256 "f2afcea5be39e70276d88d2ac0046f055ae0e9735dbfe45b19db4491fd649731"
    end
    on_intel do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.2/sysinit.wezterm_provider_zmx_0.1.2_linux_amd64.tar.gz"
      sha256 "b958c779e3d1f9f1784ea83dd6aecc8a9c7cc5a465f1593c719967a39ca67908"
    end
  end

  def install
    libexec.install "zmx-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/zmx.json"
    (bin/"zmx-picker").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{formula_opt_bin("uv")}/uv" --no-cache run --offline --no-managed-python --no-python-downloads --no-project \\
        --python "#{formula_opt_bin("python@3.13")}/python3.13" --script "#{libexec}/zmx-picker" "$@"
    SH
    (bin/"zmx-picker").chmod 0755
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/zmx-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
