# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class SysinitWeztermProviderZoxide < Formula
  desc "Open zoxide directories from the WezTerm picker"
  homepage "https://github.com/roshbhatia/sysinit.wezterm"
  url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.1/sysinit.wezterm_provider_zoxide_0.1.1_darwin_arm64.tar.gz"
  sha256 "d95fb9db4952f641003f29a4069286ebe6ce15cd48f971a611143cedeb53ba4d"
  license "MIT"
  revision 1

  depends_on "python@3.13"
  depends_on "uv"
  depends_on "zoxide"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.1/sysinit.wezterm_provider_zoxide_0.1.1_darwin_arm64.tar.gz"
      sha256 "d95fb9db4952f641003f29a4069286ebe6ce15cd48f971a611143cedeb53ba4d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.1/sysinit.wezterm_provider_zoxide_0.1.1_linux_arm64.tar.gz"
      sha256 "d326e54849c051a38696fbf335259c36eec22bf0f6b2bd354530eb27a879cdfc"
    end
    on_intel do
      url "https://github.com/roshbhatia/sysinit.wezterm/releases/download/v0.1.1/sysinit.wezterm_provider_zoxide_0.1.1_linux_amd64.tar.gz"
      sha256 "98f9f23d41731ace047e98e359dfae1f23cf2bc949cd297e8b7474bd39d6b2ba"
    end
  end

  def install
    libexec.install "zoxide-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/zoxide.json"
    (bin/"zoxide-picker").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{formula_opt_bin("uv")}/uv" --no-cache run --offline --no-managed-python --no-python-downloads --no-project \\
        --python "#{formula_opt_bin("python@3.13")}/python3.13" --script "#{libexec}/zoxide-picker" "$@"
    SH
    (bin/"zoxide-picker").chmod 0755
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/zoxide-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
