# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TetherProviderWezterm < Formula
  desc "Open remote hosts from the WezTerm picker"
  homepage "https://github.com/roshbhatia/tether"
  url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_provider_wezterm_0.3.1_darwin_arm64.tar.gz"
  sha256 "341937b454ffcb7db65270e2c30727a0ace4fef5d34bb6312e8667f4d9d6d47d"
  license "MIT"

  depends_on "roshbhatia/tap/tether"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_provider_wezterm_0.3.1_darwin_arm64.tar.gz"
      sha256 "341937b454ffcb7db65270e2c30727a0ace4fef5d34bb6312e8667f4d9d6d47d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_provider_wezterm_0.3.1_linux_arm64.tar.gz"
      sha256 "a9f2f67d60c37a6fa444972d5f9342c5f36670eac6468937239b214898fa48f6"
    end
    on_intel do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_provider_wezterm_0.3.1_linux_amd64.tar.gz"
      sha256 "4c5c90f2e55086fe6f0da66d4f256d26cba38dd65bb340a8a1571a38a39b8642"
    end
  end

  def install
    bin.install "tether-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/tether.json"
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/tether-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
