# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TetherAll < Formula
  desc "All providers for tether"
  homepage "https://github.com/roshbhatia/tether"
  url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_0.3.1_darwin_arm64.tar.gz"
  sha256 "11af9f29372e9d35869f0e9917c7a908806c0650694574c367be2738059344f9"
  license "MIT"

  depends_on "roshbhatia/tap/tether"
  depends_on "roshbhatia/tap/tether-provider-wezterm"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_0.3.1_darwin_arm64.tar.gz"
      sha256 "11af9f29372e9d35869f0e9917c7a908806c0650694574c367be2738059344f9"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_0.3.1_linux_arm64.tar.gz"
      sha256 "4a74b0e92d7070a4b1cb45c082223b64806c74636d22d82886b9d1af72064eef"
    end
    on_intel do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.1/tether_0.3.1_linux_amd64.tar.gz"
      sha256 "8c17dc02a23d8f74cecb26e32bb40b544417a03721b40fa35ceee3a7462f16ca"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      tether
      tether-provider-wezterm
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
