# This file is generated by hack/update.rb. Edit packages.yml instead.
class TetherAll < Formula
  desc "tether with all provider packages"
  homepage "https://github.com/roshbhatia/tether"
  url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_0.3.0_darwin_arm64.tar.gz"
  sha256 "0836160f349939f73731fce08f004f784608621ec14976bfa16fc46834bd5c68"
  license "MIT"

  depends_on "roshbhatia/tap/tether"
  depends_on "roshbhatia/tap/tether-provider-wezterm"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_0.3.0_darwin_arm64.tar.gz"
      sha256 "0836160f349939f73731fce08f004f784608621ec14976bfa16fc46834bd5c68"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_0.3.0_linux_arm64.tar.gz"
      sha256 "ea67bd48734fe9955ea9068b1abc40d19a79be7a8bd3166ed889d7e2871a31a1"
    end
    on_intel do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_0.3.0_linux_amd64.tar.gz"
      sha256 "3d181225c0420472cc1a7c9d4ec0279798d1bcce7844578ffbafc11c59d20273"
    end
  end

  def install
    (pkgshare/"providers.txt").write "tether\ntether-provider-wezterm\n"
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
