# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TetherProviderWezterm < Formula
  desc "Select a development host for the repair task"
  homepage "https://github.com/roshbhatia/tether"
  url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_provider_wezterm_0.3.0_darwin_arm64.tar.gz"
  sha256 "d07861ff6eaff2ab3a74bfea1b30645bc4999c7ce877e6db418628e756eb3ef6"
  license "MIT"

  depends_on "python@3.13"
  depends_on "roshbhatia/tap/tether"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_provider_wezterm_0.3.0_darwin_arm64.tar.gz"
      sha256 "d07861ff6eaff2ab3a74bfea1b30645bc4999c7ce877e6db418628e756eb3ef6"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_provider_wezterm_0.3.0_linux_arm64.tar.gz"
      sha256 "80673be276db98b1aa51ee5856d8154a76333057d21454ad549cae34916af8c5"
    end
    on_intel do
      url "https://github.com/roshbhatia/tether/releases/download/v0.3.0/tether_provider_wezterm_0.3.0_linux_amd64.tar.gz"
      sha256 "3dfa11e0e1696ed159b937b0e41442ef9c8e8ec78c8070a4c8adaa072ec80558"
    end
  end

  def install
    libexec.install "tether-picker"
    (share/"wezterm/providers").install "share/wezterm/providers/tether.json"
    (bin/"tether-picker").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{formula_opt_bin("python@3.13")}/python3.13" "#{libexec}/tether-picker" "$@"
    SH
    (bin/"tether-picker").chmod 0755
  end

  test do
    request = {
      version: "provider/v1", kind: "request", requestId: "brew-test",
      capability: "picker.describe", input: {}
    }.to_json
    response = JSON.parse(pipe_output("#{bin}/tether-picker", request, 0))
    assert_equal "brew-test", response.fetch("requestId")
    assert_equal "ok", response.fetch("status")
    assert_predicate response.fetch("output").fetch("title"), :present?
  end
end
