# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderCodex < Formula
  desc "Read a token parser repair from a Codex transcript"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_codex_0.11.1_darwin_arm64.tar.gz"
  sha256 "2d9da09e43facf8bf63f0d789c65a97800b32288e9c827adc5341665e58fb1ad"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_codex_0.11.1_darwin_arm64.tar.gz"
      sha256 "2d9da09e43facf8bf63f0d789c65a97800b32288e9c827adc5341665e58fb1ad"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_codex_0.11.1_linux_arm64.tar.gz"
      sha256 "bbcefa1cd5233824493c97e26964f3c96fd2a083224d89473f16eab36320c55a"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_codex_0.11.1_linux_amd64.tar.gz"
      sha256 "f4614198f5397d14cf96da3fcec9e727126e1f6ab57df73efb8abd36a7116b72"
    end
  end

  def install
    bin.install "traces-provider-codex"
    (share/"traces/providers/codex").install "share/traces/providers/codex/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-codex"
  end
end
