# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesWorklog < Formula
  desc "Summarize Claude Code session work"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_tool_worklog_0.11.2_darwin_arm64.tar.gz"
  sha256 "371f374b7d95c190a0bbfe2d99b7d824afe93d0de853809c61bb4976818430e3"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_tool_worklog_0.11.2_darwin_arm64.tar.gz"
      sha256 "371f374b7d95c190a0bbfe2d99b7d824afe93d0de853809c61bb4976818430e3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_tool_worklog_0.11.2_linux_arm64.tar.gz"
      sha256 "e9d9e87268dba35b37f62be909abdd95420e4d98f86473696b7a327619fd0a37"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_tool_worklog_0.11.2_linux_amd64.tar.gz"
      sha256 "5ed764402dcbb25f0daa6d0494dc3c648317e401e9abeaac76c5baa788eb354c"
    end
  end

  def install
    bin.install "traces-worklog"
  end

  test do
    assert_match "traces-worklog", shell_output("#{bin}/traces-worklog --help 2>&1")
  end
end
