# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderDevin < Formula
  desc "Read Devin CLI session activity and directory sessions"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_devin_0.11.2_darwin_arm64.tar.gz"
  sha256 "d77c77fd6cb1c74e124708053c071495e58694897ec8e8d9f9ea4a0d9d7d7daf"
  license "MIT"

  depends_on "sqlite"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_devin_0.11.2_darwin_arm64.tar.gz"
      sha256 "d77c77fd6cb1c74e124708053c071495e58694897ec8e8d9f9ea4a0d9d7d7daf"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_devin_0.11.2_linux_arm64.tar.gz"
      sha256 "22c7c6e9ea0e623e253bf7b8c77ba34e9753d401eeab14d7da12298d166baecb"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_devin_0.11.2_linux_amd64.tar.gz"
      sha256 "23b22c7c357ff745e6cb185eaf8da370629f597cdb6fb8872055ddd5e1132ffe"
    end
  end

  def install
    bin.install "traces-provider-devin"
    (share/"traces/providers/devin").install "share/traces/providers/devin/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-devin"
  end
end
