# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderAntigravity < Formula
  desc "Replay an offline token parser review with antigravity"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_antigravity_0.11.1_darwin_arm64.tar.gz"
  sha256 "53ffa93a530b3eeca3bb57e15da28495a579f09daa7780ebbdf1c55ec94abb7a"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_antigravity_0.11.1_darwin_arm64.tar.gz"
      sha256 "53ffa93a530b3eeca3bb57e15da28495a579f09daa7780ebbdf1c55ec94abb7a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_antigravity_0.11.1_linux_arm64.tar.gz"
      sha256 "ded9cbe76bea273181f15b3874ff6b08c79055f46b19370bc07777681af83e83"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_antigravity_0.11.1_linux_amd64.tar.gz"
      sha256 "5801dbcb75930e7c29fca22e3c058f50f719c365cbb8f14d3665a750a7fa1a5c"
    end
  end

  def install
    bin.install "traces-provider-antigravity"
    (share/"traces/providers/antigravity").install "share/traces/providers/antigravity/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-antigravity"
  end
end
