# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderDevin < Formula
  desc "Replay an offline token parser review with devin"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_devin_0.11.1_darwin_arm64.tar.gz"
  sha256 "c46800a21782f9a74bc07df4cf39d5c589d57f43ab4987f0a2cf6dd87853c387"
  license "MIT"

  depends_on "sqlite"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_devin_0.11.1_darwin_arm64.tar.gz"
      sha256 "c46800a21782f9a74bc07df4cf39d5c589d57f43ab4987f0a2cf6dd87853c387"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_devin_0.11.1_linux_arm64.tar.gz"
      sha256 "f999b2c6d566abd6ec3312f3891da203512ba0af59ada7d843c6da5361a6a0bf"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_devin_0.11.1_linux_amd64.tar.gz"
      sha256 "a0fed1ea97420e44c19687b661f49f25f79fb546a41d80ee7aa7d940d8527999"
    end
  end

  def install
    bin.install "traces-provider-devin"
    (share/"traces/providers/devin").install "share/traces/providers/devin/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-devin"
  end
end
