# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderCodex < Formula
  desc "Read Codex rollout activity"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_codex_0.11.2_darwin_arm64.tar.gz"
  sha256 "bce94b450eaa8b84e2b9b7f84126c64402bd013e37f5e56d287a970591794546"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_codex_0.11.2_darwin_arm64.tar.gz"
      sha256 "bce94b450eaa8b84e2b9b7f84126c64402bd013e37f5e56d287a970591794546"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_codex_0.11.2_linux_arm64.tar.gz"
      sha256 "31ea73be25a83d6cbee041f7cb90cca7b92da11476012ed2f983f619c2409792"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_codex_0.11.2_linux_amd64.tar.gz"
      sha256 "a2c8a63926bbe48913080969d4d21987a4a257efdfe6a3781d39f9fdcbb804ef"
    end
  end

  def install
    bin.install "traces-provider-codex"
    (share/"traces/providers/codex").install "share/traces/providers/codex/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-codex"
  end
end
