# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderGate < Formula
  desc "Read gate hook decisions as activity"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_gate_0.11.2_darwin_arm64.tar.gz"
  sha256 "9d11c9d63ce4dfab85660b46eb24d95685327ab05f549c7db652b15532524ac6"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_gate_0.11.2_darwin_arm64.tar.gz"
      sha256 "9d11c9d63ce4dfab85660b46eb24d95685327ab05f549c7db652b15532524ac6"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_gate_0.11.2_linux_arm64.tar.gz"
      sha256 "9cfb841760d7841dc6922960085813699e5a7b53524ca88511926fbbd702d02e"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_gate_0.11.2_linux_amd64.tar.gz"
      sha256 "288af10820df1132a11967ffee76d13c04abe9485d68945915bd1c6cbce7987c"
    end
  end

  def install
    bin.install "traces-provider-gate"
    (share/"traces/providers/gate").install "share/traces/providers/gate/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-gate"
  end
end
