# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderOpencode < Formula
  desc "Read OpenCode exported session activity"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_opencode_0.11.2_darwin_arm64.tar.gz"
  sha256 "ac461063f89036ec00f32db06fc12089c93d0d381fffb5899d6823f619702477"
  license "MIT"

  depends_on "opencode"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_opencode_0.11.2_darwin_arm64.tar.gz"
      sha256 "ac461063f89036ec00f32db06fc12089c93d0d381fffb5899d6823f619702477"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_opencode_0.11.2_linux_arm64.tar.gz"
      sha256 "e3ad2e61876caf677c1959f037f710a0c6922d943ce99dd4b6375012096d7c7e"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_opencode_0.11.2_linux_amd64.tar.gz"
      sha256 "96e22f0f013080787527b1b0e3185d47fb9490377e55ea6171ca48ebebb1d64a"
    end
  end

  def install
    bin.install "traces-provider-opencode"
    (share/"traces/providers/opencode").install "share/traces/providers/opencode/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-opencode"
  end
end
