# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderOpencode < Formula
  desc "Read an offline token parser review export"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_opencode_0.11.1_darwin_arm64.tar.gz"
  sha256 "fbeda9c5e6c2427ad7567b11e118d5636fa58568358afc9c85622b1bc7ca7837"
  license "MIT"

  depends_on "opencode"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_opencode_0.11.1_darwin_arm64.tar.gz"
      sha256 "fbeda9c5e6c2427ad7567b11e118d5636fa58568358afc9c85622b1bc7ca7837"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_opencode_0.11.1_linux_arm64.tar.gz"
      sha256 "a3c84f36614da957bdd7b6f9fc46e21014154486878b8d20658fed49ca8aab43"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_opencode_0.11.1_linux_amd64.tar.gz"
      sha256 "12ebeb2ada4349d2387a9f49fdde5c5b54485f85b4469984131dd3994db0aa43"
    end
  end

  def install
    bin.install "traces-provider-opencode"
    (share/"traces/providers/opencode").install "share/traces/providers/opencode/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-opencode"
  end
end
