# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderCursor < Formula
  desc "Read Cursor CLI transcript activity and directory sessions"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_cursor_0.11.2_darwin_arm64.tar.gz"
  sha256 "3b0a13bc9defc72fad68ed794fc3fd1474830278c7cf11e3dd89f3d055f5a94b"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_cursor_0.11.2_darwin_arm64.tar.gz"
      sha256 "3b0a13bc9defc72fad68ed794fc3fd1474830278c7cf11e3dd89f3d055f5a94b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_cursor_0.11.2_linux_arm64.tar.gz"
      sha256 "b448a2a7fa1cde5e621a5bb48f3c9726814d739613515d4fdf9b9f71319d5eff"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_cursor_0.11.2_linux_amd64.tar.gz"
      sha256 "d58936c479a5a76c2e90501014489475afa30fbf705422837afc207af59d9f77"
    end
  end

  def install
    bin.install "traces-provider-cursor"
    (share/"traces/providers/cursor").install "share/traces/providers/cursor/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-cursor"
  end
end
