# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderGit < Formula
  desc "Render a two-file diff with Git"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_git_0.11.2_darwin_arm64.tar.gz"
  sha256 "0c4b8de8af58023e478f3e562993104cd5f67f3876c4a76eeaa99c2949aefcef"
  license "MIT"

  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_git_0.11.2_darwin_arm64.tar.gz"
      sha256 "0c4b8de8af58023e478f3e562993104cd5f67f3876c4a76eeaa99c2949aefcef"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_git_0.11.2_linux_arm64.tar.gz"
      sha256 "aeb264fef9b7553b84e4a7b49dbde6e03ddce4bc53d1c54a2a8f5be0f4ea43cb"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_git_0.11.2_linux_amd64.tar.gz"
      sha256 "e4f45a766468f3c9099bcdf58c7a3ab0b4442bc3f0256cde102b831437c1abcb"
    end
  end

  def install
    bin.install "traces-provider-git"
    (share/"traces/providers/git").install "share/traces/providers/git/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-git"
  end
end
