# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderGate < Formula
  desc "Replay an offline token parser review with gate"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_gate_0.11.1_darwin_arm64.tar.gz"
  sha256 "b61ac278083a7d1876d7ec5ab866f7d2156fc1ccb44ed6bac167389c5e7bc941"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_gate_0.11.1_darwin_arm64.tar.gz"
      sha256 "b61ac278083a7d1876d7ec5ab866f7d2156fc1ccb44ed6bac167389c5e7bc941"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_gate_0.11.1_linux_arm64.tar.gz"
      sha256 "6325f986d7e188b19caedbc6406f0516a9c68ecebb8060e4f496c27f629832dd"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_gate_0.11.1_linux_amd64.tar.gz"
      sha256 "448b617590f74b513167030ab11fb189dfd668280154c2a2d82d95ce53d42acc"
    end
  end

  def install
    bin.install "traces-provider-gate"
    (share/"traces/providers/gate").install "share/traces/providers/gate/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-gate"
  end
end
