# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesAll < Formula
  desc "traces with all provider packages"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_darwin_arm64.tar.gz"
  sha256 "e86c0b915e04787d6369ee96e8cba8bdfb75ee9a385bc73bae6aee678d0b731e"
  license "MIT"

  depends_on "roshbhatia/tap/traces"
  depends_on "roshbhatia/tap/traces-provider-antigravity"
  depends_on "roshbhatia/tap/traces-provider-claude"
  depends_on "roshbhatia/tap/traces-provider-codex"
  depends_on "roshbhatia/tap/traces-provider-cursor"
  depends_on "roshbhatia/tap/traces-provider-desktop"
  depends_on "roshbhatia/tap/traces-provider-devin"
  depends_on "roshbhatia/tap/traces-provider-gate"
  depends_on "roshbhatia/tap/traces-provider-git"
  depends_on "roshbhatia/tap/traces-provider-opencode"
  depends_on "roshbhatia/tap/traces-worklog"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_darwin_arm64.tar.gz"
      sha256 "e86c0b915e04787d6369ee96e8cba8bdfb75ee9a385bc73bae6aee678d0b731e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_linux_arm64.tar.gz"
      sha256 "f708a876d1c0c012944b38f1826e968527be710a59827b5c2a0289311c5e9e66"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_linux_amd64.tar.gz"
      sha256 "2d4cfcc2620c2c0ef062f78b1b3a37a7e905e973290a6dc620c3e1e38f5ecafe"
    end
  end

  def install
    (pkgshare/"providers.txt").write "traces\ntraces-provider-antigravity\ntraces-provider-claude\ntraces-provider-codex\ntraces-provider-cursor\ntraces-provider-desktop\ntraces-provider-devin\ntraces-provider-gate\ntraces-provider-git\ntraces-provider-opencode\ntraces-worklog\n"
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
