# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class Traces < Formula
  desc "Inspect agent activity as a trace tree"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_darwin_arm64.tar.gz"
  sha256 "e86c0b915e04787d6369ee96e8cba8bdfb75ee9a385bc73bae6aee678d0b731e"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_darwin_arm64.tar.gz"
      sha256 "e86c0b915e04787d6369ee96e8cba8bdfb75ee9a385bc73bae6aee678d0b731e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_linux_arm64.tar.gz"
      sha256 "f708a876d1c0c012944b38f1826e968527be710a59827b5c2a0289311c5e9e66"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_0.11.1_linux_amd64.tar.gz"
      sha256 "2d4cfcc2620c2c0ef062f78b1b3a37a7e905e973290a6dc620c3e1e38f5ecafe"
    end
  end

  def install
    libexec.install "traces"
    generate_completions_from_executable(libexec/"traces", "completion")
    nu_completion = buildpath/"traces.nu"
    nu_completion.write Utils.safe_popen_read(libexec/"traces", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
    (bin/"traces").write <<~SH
      #!/bin/sh
      export XDG_DATA_DIRS="#{HOMEBREW_PREFIX}/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      exec "#{libexec}/traces" "$@"
    SH
    (bin/"traces").chmod 0755
  end

  test do
    assert_match "traces", shell_output("#{bin}/traces --help 2>&1")
  end
end
