# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderCursor < Formula
  desc "Replay an offline token parser review with cursor"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_cursor_0.11.1_darwin_arm64.tar.gz"
  sha256 "a2686aa614a94949b664caf69f29091ecb7a09ca7ed65acc2058c8f58a85b83d"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_cursor_0.11.1_darwin_arm64.tar.gz"
      sha256 "a2686aa614a94949b664caf69f29091ecb7a09ca7ed65acc2058c8f58a85b83d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_cursor_0.11.1_linux_arm64.tar.gz"
      sha256 "eb1e7f3bf8259bbffef930e93bacf1dec348368df5a44c5ce1de12094c3575f9"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_cursor_0.11.1_linux_amd64.tar.gz"
      sha256 "b14e6bbfcb27f32b496d74652f28789ad154d4d3a16e71c943430f7175e2124e"
    end
  end

  def install
    bin.install "traces-provider-cursor"
    (share/"traces/providers/cursor").install "share/traces/providers/cursor/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-cursor"
  end
end
