# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderDesktop < Formula
  desc "Copy text and open documents through host desktop commands"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_desktop_0.11.2_darwin_arm64.tar.gz"
  sha256 "caa03e813a58e977139c88f203929d569d5b6d563dba69d60e9405accc52a098"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_desktop_0.11.2_darwin_arm64.tar.gz"
      sha256 "caa03e813a58e977139c88f203929d569d5b6d563dba69d60e9405accc52a098"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_desktop_0.11.2_linux_arm64.tar.gz"
      sha256 "adfa90b7166773afa8230db6b593164350919060f0cf503ac2900d90029cc17e"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_desktop_0.11.2_linux_amd64.tar.gz"
      sha256 "0b8fe0ef086ccedb44e6e792b6106f0499b350f81196a9cf213983a6e628e24a"
    end
  end

  def install
    bin.install "traces-provider-desktop"
    (share/"traces/providers/desktop").install "share/traces/providers/desktop/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-desktop"
  end
end
