# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderAntigravity < Formula
  desc "Read Antigravity CLI trajectory activity and directory sessions"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_antigravity_0.11.2_darwin_arm64.tar.gz"
  sha256 "4939fa9a24e1610dfaef0a2ebfd758d63737ab04bf66bad93ec800ea776d790e"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_antigravity_0.11.2_darwin_arm64.tar.gz"
      sha256 "4939fa9a24e1610dfaef0a2ebfd758d63737ab04bf66bad93ec800ea776d790e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_antigravity_0.11.2_linux_arm64.tar.gz"
      sha256 "c78031f7ea58e80b8b27cc06bd578ce13ba19c86e0277e8aecedf0ad3747e226"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_antigravity_0.11.2_linux_amd64.tar.gz"
      sha256 "e8647c34c962f96b4d8310a5cd51e6b6ec4f11898ea18d719437707f5c7b31c4"
    end
  end

  def install
    bin.install "traces-provider-antigravity"
    (share/"traces/providers/antigravity").install "share/traces/providers/antigravity/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-antigravity"
  end
end
