# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesAll < Formula
  desc "All providers for traces"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_0.11.2_darwin_arm64.tar.gz"
  sha256 "809d4e148c2148802be53d60c6d8833612ef00fd3862d90b42a85e1fb21c27de"
  license "MIT"

  depends_on "roshbhatia/tap/traces"
  depends_on "roshbhatia/tap/traces-provider-antigravity"
  depends_on "roshbhatia/tap/traces-provider-claude"
  depends_on "roshbhatia/tap/traces-provider-codex"
  depends_on "roshbhatia/tap/traces-provider-cursor"
  depends_on "roshbhatia/tap/traces-provider-desktop"
  depends_on "roshbhatia/tap/traces-provider-devin"
  depends_on "roshbhatia/tap/traces-provider-gate"
  depends_on "roshbhatia/tap/traces-provider-git"
  depends_on "roshbhatia/tap/traces-provider-opencode"
  depends_on "roshbhatia/tap/traces-worklog"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_0.11.2_darwin_arm64.tar.gz"
      sha256 "809d4e148c2148802be53d60c6d8833612ef00fd3862d90b42a85e1fb21c27de"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_0.11.2_linux_arm64.tar.gz"
      sha256 "4c2d9557a11ff54bba73d10ed8e77cf9ba43aa0aa509fe2a14ea1277ebd51245"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_0.11.2_linux_amd64.tar.gz"
      sha256 "e340cd9bf7ecdae116920baf262196f5d5559b2d75d242eaf9b62cd548662aa7"
    end
  end

  def install
    (pkgshare/"providers.txt").write <<~TEXT
      traces
      traces-provider-antigravity
      traces-provider-claude
      traces-provider-codex
      traces-provider-cursor
      traces-provider-desktop
      traces-provider-devin
      traces-provider-gate
      traces-provider-git
      traces-provider-opencode
      traces-worklog
    TEXT
  end

  test do
    assert_path_exists pkgshare/"providers.txt"
  end
end
