# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderGit < Formula
  desc "Inspect the token parser patch"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_git_0.11.1_darwin_arm64.tar.gz"
  sha256 "339e8c8e4ee2269a0756c46984caea3545d71037871137c80808f4f430c15c4c"
  license "MIT"

  depends_on "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_git_0.11.1_darwin_arm64.tar.gz"
      sha256 "339e8c8e4ee2269a0756c46984caea3545d71037871137c80808f4f430c15c4c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_git_0.11.1_linux_arm64.tar.gz"
      sha256 "19d2f3b20d34e158491e4fa1cee506fe75b68fade9c8efa9498f22c838bd7a0b"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_git_0.11.1_linux_amd64.tar.gz"
      sha256 "4f57e8a2583e75fb27a611a61c00f5bb4a2ec489b3392a93fa13dfe30f04bdb7"
    end
  end

  def install
    bin.install "traces-provider-git"
    (share/"traces/providers/git").install "share/traces/providers/git/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-git"
  end
end
