# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderDesktop < Formula
  desc "Open the saved token parser review report"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_desktop_0.11.1_darwin_arm64.tar.gz"
  sha256 "91058bbcfd55faf31cb842f61bbbaef34b69b71f46cbffe0338af20f2c9efcd8"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_desktop_0.11.1_darwin_arm64.tar.gz"
      sha256 "91058bbcfd55faf31cb842f61bbbaef34b69b71f46cbffe0338af20f2c9efcd8"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_desktop_0.11.1_linux_arm64.tar.gz"
      sha256 "19dd97280f168c252182a74cfcfb2387a8dec23015832a6bea3fe07443bab02e"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_desktop_0.11.1_linux_amd64.tar.gz"
      sha256 "d3ee866f5a6086747f2d149ee86a98b6df374e74bc404dc392a6f78d7dc5a9c9"
    end
  end

  def install
    bin.install "traces-provider-desktop"
    (share/"traces/providers/desktop").install "share/traces/providers/desktop/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-desktop"
  end
end
