# This file is generated by hack/update.rb. Edit packages.yml instead.
class Traces < Formula
  desc "Inspect agent activity as a trace tree"
  homepage "https://github.com/roshbhatia/traces"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.5.1/traces_0.5.1_darwin_arm64.tar.gz"
      sha256 "875b53fdc0b2131ea7fecb3070954e1073be39ccd6b049d5ff1374a8cd5ded8c"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.5.1/traces_0.5.1_darwin_amd64.tar.gz"
      sha256 "fa9704c6caa88b7b9cc8d9703deca4fa682765b1c2cf83f452a3f2dd958a9e5f"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.5.1/traces_0.5.1_linux_arm64.tar.gz"
      sha256 "bf99bdc1c5a380e4e6a461da64e39c354ca55a61194448e2f6c04133ac4f8ee2"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.5.1/traces_0.5.1_linux_amd64.tar.gz"
      sha256 "878d9d758728eaf750431e149f5a30e01c293ffbb2a72c2e968c994606b4360b"
    end
  end

  def install
    bin.install "traces"
    generate_completions_from_executable(bin/"traces", "completion")
    nu_completion = buildpath/"traces.nu"
    nu_completion.write Utils.safe_popen_read(bin/"traces", "completion", "nu")
    (share/"nushell/vendor/autoload").install nu_completion
  end

  test do
    assert_match "traces", shell_output("#{bin}/traces --help")
  end
end
