# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderClaude < Formula
  desc "Read a token parser review from a Claude transcript"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_claude_0.11.1_darwin_arm64.tar.gz"
  sha256 "de18e3ac6a796c9b77480fa98200602d8cd1813ced0ca16c25882f14079521ca"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_claude_0.11.1_darwin_arm64.tar.gz"
      sha256 "de18e3ac6a796c9b77480fa98200602d8cd1813ced0ca16c25882f14079521ca"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_claude_0.11.1_linux_arm64.tar.gz"
      sha256 "2f9546940500a8bbd3e08b79bb19d751900138e468102ebe5848cbab2202daed"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_provider_claude_0.11.1_linux_amd64.tar.gz"
      sha256 "48f874bad3cd66bf5379cecd156034ff51ebf734028df85e61958f310226fec3"
    end
  end

  def install
    bin.install "traces-provider-claude"
    (share/"traces/providers/claude").install "share/traces/providers/claude/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-claude"
  end
end
