# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesWorklog < Formula
  desc "Replay an offline token parser review with worklog"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_tool_worklog_0.11.1_darwin_arm64.tar.gz"
  sha256 "f1a04e6aa6fae602d26e54867b74227964c2d3b7cf9de7de74f5548188a792bb"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_tool_worklog_0.11.1_darwin_arm64.tar.gz"
      sha256 "f1a04e6aa6fae602d26e54867b74227964c2d3b7cf9de7de74f5548188a792bb"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_tool_worklog_0.11.1_linux_arm64.tar.gz"
      sha256 "bcdb7bdba0aa1433002253b45386cd16bd5dcdfc47ac774d9e5ec0e0d58acb57"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.1/traces_tool_worklog_0.11.1_linux_amd64.tar.gz"
      sha256 "3708c4ab02e4f0f29fafe720682e73ad317fbc12c77e0a38a3e4f30fb19d64f3"
    end
  end

  def install
    bin.install "traces-worklog"
  end

  test do
    assert_match "traces-worklog", shell_output("#{bin}/traces-worklog --help 2>&1")
  end
end
