# frozen_string_literal: true

# This file is generated by hack/update.rb. Edit packages.yml instead.
class TracesProviderClaude < Formula
  desc "Read Claude Code transcript activity and directory sessions"
  homepage "https://github.com/roshbhatia/traces"
  url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_claude_0.11.2_darwin_arm64.tar.gz"
  sha256 "531f6a7487b6678fd8aaa16c0c01960c92199c9a258998d151f724cb431e4889"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_claude_0.11.2_darwin_arm64.tar.gz"
      sha256 "531f6a7487b6678fd8aaa16c0c01960c92199c9a258998d151f724cb431e4889"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_claude_0.11.2_linux_arm64.tar.gz"
      sha256 "6a158e80a691f0cffc00850aef1c1902ae6e3eebb0c55d8a455e8dbb876a050a"
    end
    on_intel do
      url "https://github.com/roshbhatia/traces/releases/download/v0.11.2/traces_provider_claude_0.11.2_linux_amd64.tar.gz"
      sha256 "c38ab41b72b9877ec03a27b137ae954a61a6ad561dbd5e024657a3a5f5123be6"
    end
  end

  def install
    bin.install "traces-provider-claude"
    (share/"traces/providers/claude").install "share/traces/providers/claude/provider.yaml"
  end

  test do
    assert_path_exists bin/"traces-provider-claude"
  end
end
